### ISSUE TITLE
LXD VMs Design + UX review

### ISSUE THREAD

**Issue by Caleb-Ellis** [canonical-web-and-design/maas-ui#1004]

**Comment by lilyvidenova** [comment]
Only one storage disk is allowed

**Comment by cristinadresch** [comment]
@lilyvidenova @Caleb-Ellis is this one still in progress?

**Comment by lilyvidenova** [comment]
Yes, I haven't done it yet

**Comment by lilyvidenova** [comment]
<img width="1680" alt="Screenshot 2020-05-11 at 10 04 38" src="https://user-images.githubusercontent.com/17980375/81546333-24223d80-9372-11ea-9448-4abaea07ce9f.png">
<img width="1680" alt="Screenshot 2020-05-11 at 10 21 09" src="https://user-images.githubusercontent.com/17980375/81546335-25536a80-9372-11ea-8e06-72c4ce4e6350.png">
<img width="1680" alt="Screenshot 2020-05-11 at 10 20 25" src="https://user-images.githubusercontent.com/17980375/81546337-25536a80-9372-11ea-8d1c-050a9e6f02dc.png">
<img width="1680" alt="Screenshot 2020-05-11 at 10 19 18" src="https://user-images.githubusercontent.com/17980375/81546339-25ec0100-9372-11ea-991a-0077019b1720.png">
<img width="1680" alt="Screenshot 2020-05-11 at 10 16 17" src="https://user-images.githubusercontent.com/17980375/81546341-25ec0100-9372-11ea-9b08-cd0bd32148d7.png">
<img width="1680" alt="Screenshot 2020-05-11 at 10 15 26" src="https://user-images.githubusercontent.com/17980375/81546342-26849780-9372-11ea-8dbf-b3d973fdbef9.png">
<img width="1680" alt="Screenshot 2020-05-11 at 10 13 18" src="https://user-images.githubusercontent.com/17980375/81546346-271d2e00-9372-11ea-811f-76348951afcf.png">
<img width="1680" alt="Screenshot 2020-05-11 at 10 12 45" src="https://user-images.githubusercontent.com/17980375/81546347-27b5c480-9372-11ea-9781-ff3607bffaae.png">
<img width="1680" alt="Screenshot 2020-05-11 at 10 12 10" src="https://user-images.githubusercontent.com/17980375/81546348-284e5b00-9372-11ea-9196-f325bf6706e2.png">
<img width="1680" alt="Screenshot 2020-05-11 at 10 11 31" src="https://user-images.githubusercontent.com/17980375/81546349-284e5b00-9372-11ea-9f8d-cce6c102dfc8.png">
<img width="1680" alt="Screenshot 2020-05-11 at 10 10 46" src="https://user-images.githubusercontent.com/17980375/81546351-28e6f180-9372-11ea-872a-f1567fe72513.png">
<img width="1680" alt="Screenshot 2020-05-11 at 10 10 02" src="https://user-images.githubusercontent.com/17980375/81546352-28e6f180-9372-11ea-95d9-a0a8289059a1.png">
<img width="1680" alt="Screenshot 2020-05-11 at 10 07 41" src="https://user-images.githubusercontent.com/17980375/81546354-297f8800-9372-11ea-90fe-2b5cbda56bf3.png">
<img width="1680" alt="Screenshot 2020-05-11 at 10 07 00" src="https://user-images.githubusercontent.com/17980375/81546357-297f8800-9372-11ea-9081-4916d61b432a.png">
<img width="1680" alt="Screenshot 2020-05-11 at 10 05 51" src="https://user-images.githubusercontent.com/17980375/81546361-2a181e80-9372-11ea-8f84-2ce9bbb9993d.png">

**Comment by cassiocassio** [comment]
This page has always been lovely :-|

We've got a couple of different kinds of "(optional)" going on here...

1. Optional host name, pool or zone - we'll choose something, and you you can easily change it later

2. Optional Cores and Optional RAM, where it's difficult to change, and where we have a Default Opinion that you may well want to override, and where you probably want to know what that default is.

Can we find a way to improve 2?

**Comment by lilyvidenova** [comment]
Just FYI @cristinadresch - this will need another review before we can release 2.8

**Comment by cristinadresch** [comment]
@lilyvidenova sounds good, we agreed we will do it as part of the release 2.8 QA
