### ISSUE TITLE
Chassis power types should be dynamically listed

### ISSUE THREAD

**Issue by Treydone** [canonical-web-and-design/maas-ui#1012]
All the chassis power types are listed in ui/src/app/machines/views/AddChassis/chassisPowerTypes.js. If we add a new chassis power types, we have to change the backend and the ui. A better way is to use the settings not on scope SETTING_SCOPE.NODE registered in each driver and available in /MAAS/api/2.0/machines/?op=power_parameters

**Comment by squidsoup** [comment]
Thanks for submitting an issue @Treydone, that's certainly something we should investigate!

**Comment by Caleb-Ellis** [comment]
Each power type returned from `general.power_types` now has a boolean field `chassis` which we can use to get a list of chassis power types.
