### ISSUE TITLE
UX exploration - Logs and Events

### ISSUE THREAD

**Issue by amylily1011** [canonical-web-and-design/maas-ui#1036]

**Comment by clagom** [comment]
Hi @amylily1011 @cristinadresch what are the next steps after completing this epic? (we can discuss during our next meeting if it requires more thinking)

**Comment by amylily1011** [comment]
@clagom after everything is completed on this epic, we will need to review the UX and Visuals for it in order for this to be ready for development by the next cycle. 

The next cycle is also when the team will focus on Machine details React code, which by the time the team starts working on it, we will at least have the finalized visual, prototype (interactions), and  loading animation ready for development. During the end of this cycle, I need to work on the documentation for the stepper and its behavior in Vanilla to prepare for the next cycle react work.  

I think the item that is missing here is the Stepper work in Vanilla, which will be my focus close to the end of this cycle. ;-)

**Comment by clagom** [comment]
Great, thanks @amylily1011, sounds good
