### ISSUE TITLE
Config not fetched if app loaded from /users

### ISSUE THREAD

**Issue by squidsoup** [canonical-web-and-design/maas-ui#104]
Config is never fetched if app loaded from /users or non config route, and config components relying on state never load.

## Steps to reproduce
1. Load app from /MAAS/users
2. Visit /MAAS/configuration/general

**Comment by huwshimi** [comment]
This could be because the config is loaded in the wrapper: https://github.com/canonical-web-and-design/maas-ui/blob/master/ui/src/app/settings/containers/Settings/Settings.js#L12

Ideally that config should be loaded by the components that need it.

**Comment by squidsoup** [comment]
> This could be because the config is loaded in the wrapper: https://github.com/canonical-web-and-design/maas-ui/blob/master/ui/src/app/settings/containers/Settings/Settings.js#L12
> 
> Ideally that config should be loaded by the components that need it.

This results in a *bit* of repetition, but it is the most efficient thing to do.
