### ISSUE TITLE
Take action does not filter machines

### ISSUE THREAD

**Issue by huwshimi** [canonical-web-and-design/maas-ui#1042]
**Describe the bug**
When opening a form from the machines 'Take action' menu the angular client filtered the machines by in:selected.

**Screenshots**
This is the angular behaviour:
<img width="1466" alt="Screen Shot 2020-04-28 at 9 32 40 am" src="https://user-images.githubusercontent.com/361637/80430968-8f601e80-8933-11ea-888d-c8ce383a2a19.png">

**Comment by cristinadresch** [comment]
@huwshimi can you add estimation to this one please

**Comment by huwshimi** [comment]
@cristinadresch thanks, done.
