### ISSUE TITLE
Add messages when users are saved

### ISSUE THREAD

**Issue by huwshimi** [canonical-web-and-design/maas-ui#108]
When a user is added/updated there should be a message on the user list.

**Comment by squidsoup** [comment]
@lilyvidenova I think we probably need a timed notification that disappears after a few seconds, or something similar, do we have existing patterns for that in maas?

**Comment by lilyvidenova** [comment]
@squidsoup, @huwshimi - yes, currently we have a notification. I'd like to keep this pattern (at least for now). So on successful addition of anything, we should show an "information notification" reading "$username added successfully." 

I'd like to do something more fancy (like highlighting the row in the table in some way) but I'll leave it in the backlog for next cycle.

**Comment by cassiocassio** [comment]
The juju desktop toasts that disappear automatically do so rather quickly. 

I can't find vanilla guidance about the timeout; if it's too fast, you feel cheated; if it's too slow, you'll waste attention and effort trying to clear it


(Adding to my a of patterns / guidance  to improve - Paris @kwm14 )
https://docs.vanillaframework.io/patterns/notification/ 

It's an open question about if self-exploding messages should even exist in the first place....

the best debate about this I could find:

https://ux.stackexchange.com/questions/11203/how-long-should-a-temporary-notification-toast-appear
