### ISSUE TITLE
"Add chassis" uses power driver parameters for a single machine

### ISSUE THREAD

**Issue by lilyvidenova** [canonical-web-and-design/maas-ui#1084]
[LP 1876680](https://bugs.launchpad.net/maas/+bug/1876680)

This is with MAAS 2.8.0~beta3-8446-g.51246e3bc.

If you go to the machine listing and choose "Add chassis", you get prompted for the domain and the power driver.

The list of power drivers are the ones that are used for "Add machine", though. So you can't actually add a chassis. For example, the virsh driver prompts for the VM ID, which you don't have in a chassis.

**Comment by Caleb-Ellis** [comment]
We should filter chassis power type fields to only those that have `scope: "bmc"` i.e. remove the ones that have `scope: "node"`.
