### ISSUE TITLE
Unable to compose LXD virtual machine with UI

### ISSUE THREAD

**Issue by amylily1011** [canonical-web-and-design/maas-ui#1105]
When I try to compose an LXD virtual machine using the UI I get an error

storage: Malformed storage constraint, "0:8()".

I can compose an LXD virtual machine using the command line without problems using the following command:

maas $PROFILE pod compose $POD_ID

https://bugs.launchpad.net/maas/+bug/1875967

**Comment by lilyvidenova** [comment]
@cristinadresch FYI, this should be fixed for 2.8 too

**Comment by Caleb-Ellis** [comment]
This is invalid due to a Makefile issue when building MAAS from the Debian packages, which is what Lee was experiencing. The bug was actually fixed weeks ago.
