### ISSUE TITLE
Unable to add LXD or Intel RSD Pod in the UI

### ISSUE THREAD

**Issue by amylily1011** [canonical-web-and-design/maas-ui#1106]
When adding a Pod to MAAS the UI always assumes the Pod is a virsh Pod. There is no way to tell the form the the Pod is an LXD or Intel RSD Pod.

![image](https://launchpadlibrarian.net/478727565/Screenshot_2020-05-07%20KVM%20maas-bionic%20MAAS.png)

(I'm not sure if Intel RSD is part of the scope, but linking this to launchpad for now.)
https://bugs.launchpad.net/maas/+bug/1877208

**Comment by lilyvidenova** [comment]
The above is no longer the latest MAAS version, can you confirm this bug is still valid with the latest master?

**Comment by lilyvidenova** [comment]
Re RSD - RSD has been moved to `add hardware` on the machine listing as of 19.10 (or 04, maybe, not sure)

**Comment by amylily1011** [comment]
Both my local MAAS and bolla worked. I'll close this bug.
