### ISSUE TITLE
Fix KVM details QA issues

### ISSUE THREAD

**Issue by Caleb-Ellis** [canonical-web-and-design/maas-ui#1110]
<img width="1680" alt="Screenshot 2020-05-11 at 10 19 18" src="https://user-images.githubusercontent.com/17980375/81546339-25ec0100-9372-11ea-991a-0077019b1720.png">
<img width="1680" alt="Screenshot 2020-05-11 at 10 16 17" src="https://user-images.githubusercontent.com/17980375/81546341-25ec0100-9372-11ea-9b08-cd0bd32148d7.png">
<img width="1680" alt="Screenshot 2020-05-11 at 10 15 26" src="https://user-images.githubusercontent.com/17980375/81546342-26849780-9372-11ea-8dbf-b3d973fdbef9.png">
<img width="1680" alt="Screenshot 2020-05-11 at 10 13 18" src="https://user-images.githubusercontent.com/17980375/81546346-271d2e00-9372-11ea-811f-76348951afcf.png">
<img width="1680" alt="Screenshot 2020-05-11 at 10 12 45" src="https://user-images.githubusercontent.com/17980375/81546347-27b5c480-9372-11ea-9781-ff3607bffaae.png">
<img width="1680" alt="Screenshot 2020-05-11 at 10 12 10" src="https://user-images.githubusercontent.com/17980375/81546348-284e5b00-9372-11ea-9196-f325bf6706e2.png">
<img width="1680" alt="Screenshot 2020-05-11 at 10 11 31" src="https://user-images.githubusercontent.com/17980375/81546349-284e5b00-9372-11ea-9f8d-cce6c102dfc8.png">
<img width="1680" alt="Screenshot 2020-05-11 at 10 10 46" src="https://user-images.githubusercontent.com/17980375/81546351-28e6f180-9372-11ea-872a-f1567fe72513.png">
<img width="1680" alt="Screenshot 2020-05-11 at 10 10 02" src="https://user-images.githubusercontent.com/17980375/81546352-28e6f180-9372-11ea-95d9-a0a8289059a1.png">
<img width="1680" alt="Screenshot 2020-05-11 at 10 07 41" src="https://user-images.githubusercontent.com/17980375/81546354-297f8800-9372-11ea-90fe-2b5cbda56bf3.png">
<img width="1680" alt="Screenshot 2020-05-11 at 10 07 00" src="https://user-images.githubusercontent.com/17980375/81546357-297f8800-9372-11ea-9081-4916d61b432a.png">

**Comment by Caleb-Ellis** [comment]
<img width="1680" alt="Screenshot 2020-05-11 at 10 15 26" src="https://user-images.githubusercontent.com/17980375/81546342-26849780-9372-11ea-8dbf-b3d973fdbef9.png">

@lilyvidenova This is another one where I'm reluctant to change because of `maasObjForm`. It's not the worst thing. We'll fix it this cycle with the React migration.

**Comment by lilyvidenova** [comment]
Happy to leave `ObjForm` related ones out, just maybe @amylily1011 keep an eye out for those little issues when these pages are rebuilt in React
