### ISSUE TITLE
Form Loading State UI Design

### ISSUE THREAD

**Issue by amylily1011** [canonical-web-and-design/maas-ui#1142]
Based on https://github.com/canonical-web-and-design/MAAS-squad/issues/1974

![image.png](https://images.zenhubusercontent.com/5e6628e0ff9a3ccb84677b2f/869aa832-93f7-41bb-9da2-2bbf6870ae74)

During the QA, we discovered that when many machines are selected to perform an action such as commissioning, testing, etc, there is a delay during loading on the form before it proceeds to the next state. That delay took ~30-40 seconds and no context was provided in the UI for the long wait. 

We want to mitigate this loading state to keep our users engaged with the UI.

**Comment by lyubomir-popov** [comment]
Design: 
https://github.com/canonical-web-and-design/maas-ui/issues/1142

**Comment by amylily1011** [comment]
Hi Lyubo, very small changes to the text just to avoid confusion.

first section: 91 of 105 machines selected
second section:
from "{Commissioning} in progress...[n] of [m] machines complete"
to "{N} of {M} machines changing status to {Commissioning}"

Possible Status:
- Commissioning
- Acquiring
- Deploying
- Releasing
- Aborting
- Testing
- Entering Rescue Mode
- Exiting Rescue Mode
- Power on
- Power off
- Tagging
- Broken
- Fixed
