### ISSUE TITLE
Build: Form Loading State

### ISSUE THREAD

**Issue by amylily1011** [canonical-web-and-design/maas-ui#1148]
From #1142

We want to build a quick fix for the form loading state to mitigate the frozen wait on the form that can take a while to load.

Design:
https://zpl.io/VQX816P

Current Loading Message:

"{Commissioning} {N} of {M} machines"

Possible Status:

Commissioning
Acquiring
Deploying
Releasing
Aborting
Testing
Entering Rescue Mode on
Exiting Rescue Mode on
Powering on
Powering off
Tagging
Marking Broken
Marking Fixed

**Comment by cristinadresch** [comment]
@Caleb-Ellis when are you able to look into this one, should we wait to QA 2.8 until you finish this?

**Comment by Caleb-Ellis** [comment]
@cristinadresch I don't think this should hold up the full QA. When I create the PR for this I'll explicitly add a "Review: Design needed" label so it can be design QA'd separately from the rest.

**Comment by Caleb-Ellis** [comment]
Hey @amylily1011, sorry but I've run into a problem that I should have noticed sooner. How should we deal with errors coming from the server? We only know if there's an error *after* the websocket request is made. In the current design it's displayed above the form fields. In the new design the form closes immediately after submitting, so if there's a problem (name entered is already in use, server is busy or whatever) you lose what you'd entered. We *could* store those form values somewhere and then re-open the form if there's an error but that seems kind of messy, UX-wise as well as code-wise.

Interested in your thoughts!

**Comment by amylily1011** [comment]
That's a very fair point @Caleb-Ellis.

If an error happens, about how long does a user need to wait to know that there is an error?

I can think of 2 scenarios:
1. We stick to the current design and show the error later (replacing the current [processing] message with the error message). 
- I'm assuming, with this scenario, either we don't store those data or we store it somewhere.
- In the case of not storing information, the checkbox is still intact, so if the user were to perform the same action again, this is an acceptable behavior. But if they need to recheck a few things in the form, this can be a redundant and an unpleasant process if it happens more than 2 times.

2. We can use this as an alternative design https://zpl.io/2pGP3RQ. 
- The problem with this design is when the form closes, users will not know the current status of the total machines commissioned. (Which in some cases may take a long time for some actions)
- We can also combine this design (without changing the message) and after the form is closed, show the first design with the message on the first design. (This way we can save the information of the form settings if it didn't go through.)

At this point, the second scenario sounds more foolproof. :-)

**Comment by Caleb-Ellis** [comment]
@amylily1011 When an error happens the user will find out immediately with a notification on top of the form fields. This is regardless of where the machine was in the list (i.e. the first or the 10th of 100).

I think for now I'll go with the second option, with the simple processing label underneath. If after a UX review it doesn't seem like enough we can consider implementing the first design as well. Still, ideally this should be handled by a batch api so we don't have to make so many requests and create a need for a spinner/processing label in the first place! :P

**Comment by amylily1011** [comment]
Alright! 
In that case, let's use the message "commissioning [n] of [m] machines"

**Comment by amylily1011** [comment]
Saw the JS code on https://github.com/canonical-web-and-design/maas-ui/pull/1215#event-3418735591.

Looks very promising ;-), no need language fix.
