### ISSUE TITLE
After deleting a device, the device list is not shown

### ISSUE THREAD

**Issue by squidsoup** [canonical-web-and-design/maas-ui#1154]
**Describe the bug**
After deleting a device, the device list retains it's "selected" filter, which means no devices are displayed in the device list.

**maas-ui version**
1.1.1

**MAAS version**
n/a

**To Reproduce**
1. Go to Devices
2. Select a device
3. Choose 'Delete' from the Take Action menu
4. Delete the device

**Expected behavior**
The full devices list should display after deleting a device.

**Screenshots**

![image](https://user-images.githubusercontent.com/130286/82856138-4ff01680-9f61-11ea-9007-04866e5b47aa.png)

**Comment by Caleb-Ellis** [comment]
This got fixed.... at some point
