### ISSUE TITLE
UI authentication session is not expiring 

### ISSUE THREAD

**Issue by amylily1011** [canonical-web-and-design/maas-ui#1156]
One of our customers made a pentesting assessment and the following recommendations were issued:

- Set session timeout to the minimal value possible depending on the context of the application.
- Avoid "infinite" session timeout.

Currently, authenticated sessions are remaining active indefinitely after their last use. If an authenticated user were to leave a browser window open without explicitly logging out of the application, another person may be able to resume that user's session several hours later simply by browsing to the MAAS UI on the same computer.

From: https://bugs.launchpad.net/maas/+bug/1852745

**Comment by huwshimi** [comment]
This is a change on the server. See: https://bugs.launchpad.net/maas/+bug/1852745/comments/1
