### ISSUE TITLE
MAAS "Images" page seems to imply that i386/20.04 is available, but it's not

### ISSUE THREAD

**Issue by Caleb-Ellis** [canonical-web-and-design/maas-ui#1159]
https://bugs.launchpad.net/maas/+bug/1877585

**Comment by Caleb-Ellis** [comment]
Upping estimate to 5 - this will need more of a reworking of the images page code than I thought, because now the architectures checkbox states depend on the selected images. As a first pass I'm thinking of just having radio buttons for each selected image under the "Architectures" heading, but interested to hear your thoughts @amylily1011 

![2020-05-27_16-08](https://user-images.githubusercontent.com/25733845/82983866-4aafcc00-a034-11ea-8c28-7566d6a2d51f.png)

**Comment by amylily1011** [comment]
I think adding radio buttons look fine (a different padding should be applied ;-) ). However, if `20.04 LTS` is selected, then `i386` should be disabled. So a user knows that 20.04/i386 is not available. (Same goes for other unavailable combinations).

**Comment by Caleb-Ellis** [comment]
Good idea @amylily1011, thanks :) 

Anyway this work will need the `bootresources.save_ubuntu` websocket handler to be updated to allow selecting architectures on a per-release basis. At the moment it only accepts a list of releases and a list of architectures with nothing linking the two.

Failing that, I can change the message in the list of selected images to be "Unavailable combination". This is obviously not ideal but at the very least the reason for the image not downloading is surfaced to the user.

**Comment by amylily1011** [comment]
@Caleb-Ellis sounds like a plan!

**Comment by cristinadresch** [comment]
@Caleb-Ellis this one should be unblocked now, will you be able to look into it before Friday?

**Comment by Caleb-Ellis** [comment]
@cristinadresch Doesn't look like it's unblocked, at least as far as my initial suggestion is concerned (radio buttons for each selected release). The bug has been reassigned to Lee so I'm assuming he's still working on it.
