### ISSUE TITLE
PXE field should not be interactive (Machine details - Network tab)

### ISSUE THREAD

**Issue by Caleb-Ellis** [canonical-web-and-design/maas-ui#1164]
In MAAS 2.7+ on a machine's network interfaces list in the UI the PXE column is a radio button, it also changes the mouse pointer when mousing over another interface in the PXE column to a finger. On machines with multiple interfaces this leads the user to believe they can select a different interface to use for PXE booting which is not the case. To add to this if you edit the interface that is the current PXE interface the PXE radio button appears and is incorrectly not selected. This should be changed to be an icon or something that is not a form field that would lead the user to believe this field can be changed in the UI.

https://bugs.launchpad.net/maas/+bug/1880765

**Comment by casual-lemon** [comment]
Should we also open this same request for MAAS 2.8?
