### ISSUE TITLE
The Take action menu has deteriorated with the last update.

### ISSUE THREAD

**Issue by amylily1011** [canonical-web-and-design/maas-ui#1174]
On version 2.8.0 ~ beta4 (8502-g.942cfc7e9). The take action menu has deteriorated with the last update.
See the attached part.
Thank's.

From: https://bugs.launchpad.net/maas/+bug/1881143

![alt text](https://launchpadlibrarian.net/481790043/Screenshot_2020-05-28%20Machines%20maas-home-lab%20MAAS.png)

**Comment by lilyvidenova** [comment]
Does this happen to any other of the menus?

**Comment by amylily1011** [comment]
Only `take action` and `add hardware` on the first page.

`take action` menu on other pages are fine.

**Comment by lilyvidenova** [comment]
![image](https://user-images.githubusercontent.com/17980375/83167045-a5febe80-a107-11ea-8d33-4703020d5f32.png)

**Comment by amylily1011** [comment]
Looks like all dropdown menus on the first page is affected.
