### ISSUE TITLE
Side menu looks disabled

### ISSUE THREAD

**Issue by lilyvidenova** [canonical-web-and-design/maas-ui#1175]
![image.png](https://images.zenhubusercontent.com/5af976724b5806bc2bd30860/808284b3-7715-41f9-b310-08a17730090a)

I assume it's now the latest Vanilla but the side menu on both Settings and User preferences look disabled.

**Comment by Caleb-Ellis** [comment]
This is an issue because the background is grey. @lyubomir-popov are there scss variables we can set so we can make the highlighted background and text a shade darker?

**Comment by lyubomir-popov** [comment]
@Caleb-Ellis not at them moment, I filed a bug: https://github.com/canonical-web-and-design/vanilla-framework/issues/3105

As for looking disabled, is there evidence to that effect, like fewer people clicking?
