### ISSUE TITLE
Remove device UI is broken

### ISSUE THREAD

**Issue by anthonydillon** [canonical-web-and-design/maas-ui#1191]
Go to http://bolla.internal:5240/MAAS/l/device/aqw6qy?area=network
Click Remove physical and the expanded table does not display.

**Comment by huwshimi** [comment]
@Caleb-Ellis I can't see a delete form that can appear for a device, is it possible that this has been broken for a while? I couldn't see any recent changes in history that might have broken this.

**Comment by cristinadresch** [comment]
@Caleb-Ellis are you going to be able to look into this before Friday, should we carry forward?

**Comment by Caleb-Ellis** [comment]
@huwshimi yeah this is also broken in 2.7 so it's been a while. =/
