### ISSUE TITLE
Add filterTerm to state for relevant entities

### ISSUE THREAD

**Issue by Caleb-Ellis** [canonical-web-and-design/maas-ui#120]
In RBAC we had a separate field in state for filter term. That way we could compose a selector for search that would include the filter term and a subset/mutated list of entities (e.g `repositories.getForSettings` or something that just renames the defaults). We should consider if we want to use the same pattern here. Regardless of the approach we should fix the original issue of repositories not being filtered by "display name".

Relevant Q in reselect README: https://github.com/reduxjs/reselect#q-how-do-i-create-a-selector-that-takes-an-argument

**Comment by anthonydillon** [comment]
This is covered
