### ISSUE TITLE
Machine listing got messed up

### ISSUE THREAD

**Issue by amylily1011** [canonical-web-and-design/maas-ui#1211]
From: https://bugs.launchpad.net/maas-ui/+bug/1881275

This is with MAAS 2.8.0~beta4 (8510-g.f5a42ccea)

I'm not sure what happened, but the machine listing got in a weird state:

  https://private-fileshare.canonical.com/~bjorn/too-many-machines.png

There should be 19 machines and 2 resource pools, but it instead showed
57 machines and 4 resource pools.

This happened on two browser tabs that both had the machine listing open.
I'm not sure what triggered it. But I see that the MAAS snap was refreshed
and thus caused a restart to happen, so it might be related to that.

In the logs I see that MAAS was updated from revision 6683 to 6723.

After debugging, it seems that the UI is not refreshing its state when it loses connection to the server and reconnects again.

**Comment by huwshimi** [comment]
Fixed by https://github.com/canonical-web-and-design/maas-ui/pull/1234
