### ISSUE TITLE
Unable to upload commissioning/test script

### ISSUE THREAD

**Issue by amylily1011** [canonical-web-and-design/maas-ui#1217]
From: https://bugs.launchpad.net/maas/+bug/1882313

A user on discourse[1] has reported that they are unable to upload a test script using the MAAS UI on Linux via drag and drop or using the file upload. They claim they can using Windows. I confirmed I'm also unable to upload a commissioning or test script using the UI on Linux however I don't have access to Windows.

OS: Ubuntu 20.04
Browser: Firefox 77.0.1+build1-0ubuntu0.20.04.1

[1] https://discourse.maas.io/t/testing-scripts-upload-error/1653

**Comment by squidsoup** [comment]
@amylily1011 could you please tell me the output of `file --mime <script-you-tried>` please?
