### ISSUE TITLE
Add KVM Host stuck in Limbo

### ISSUE THREAD

**Issue by amylily1011** [canonical-web-and-design/maas-ui#1220]
I tried to add a KVM using a random address that MAAS cannot find and got stuck in limbo.
Can we add a cancel button on this form? Will the cancel button work to interrupt the request?

![image.png](https://images.zenhubusercontent.com/5e6628e0ff9a3ccb84677b2f/3f536579-8717-4089-9c70-9548270ecb36)

**Comment by squidsoup** [comment]
@amylily1011 I'm not certain we can cancel the request (the form should show a timeout eventually), but we could potentially close the form, and ignore the reponse.

**Comment by squidsoup** [comment]
This isn't blocking the release, so going to drop this from the 2.8 epic.

**Comment by squidsoup** [comment]
Closing as the react form has a different behaviour.
