### ISSUE TITLE
Add machine validate form on cancel

### ISSUE THREAD

**Issue by amylily1011** [canonical-web-and-design/maas-ui#1221]
When I put the mac address and/or the name on this form and clicked `cancel`, the form validates the mac address format, instead of closing the form. So I had to click cancel twice instead of once.

Expected behavior: when `cancel` is clicked the form should collapse/close.

![image.png](https://images.zenhubusercontent.com/5e6628e0ff9a3ccb84677b2f/8b9f7c92-50b8-4159-b157-a5d36b006a57)

**Comment by Caleb-Ellis** [comment]
I think this is probably the same issue that's causing https://github.com/canonical-web-and-design/maas-ui/issues/1043 - validation is only running on blur. Not sure why it's preventing the cancel button from working though.

**Comment by squidsoup** [comment]
Dropping this from 2.8 release as not a critical bug.

**Comment by huwshimi** [comment]
This still appears to be an issue, but I'm not really sure what the solution is. The problem seems to be that the cancel button gets moved down the page by the error message when you click on on the cancel button. If you click right at the bottom of the cancel button it closes the form.

**Comment by Caleb-Ellis** [comment]
This no longer seems to be happening. I think this was fixed when the other "Add machine" validation bug was fixed (validation had to run before you could add a manual machine, even though it had no fields)
