### ISSUE TITLE
Clearing legacy data on ws reconnect may prevent issues

### ISSUE THREAD

**Issue by huwshimi** [canonical-web-and-design/maas-ui#1235]
In the legacy client it might be prudent to clear data received from the websocket when the connection is lost to prevent possible duplication of data.

See: https://github.com/canonical-web-and-design/maas-ui/issues/1222
See: https://github.com/canonical-web-and-design/maas-ui/issues/1211

**Comment by Caleb-Ellis** [comment]
Adding this to the React migration epic - this'll be fixed when we delete legacy
