### ISSUE TITLE
Update release script to update all workspace package.jsons

### ISSUE THREAD

**Issue by Caleb-Ellis** [canonical-web-and-design/maas-ui#1237]
When releasing a new version of maas-ui, we need to update the version number in 10 places across `package.json`, `legacy/package.json`, `proxy/package.json`, `root/package.json`, `shared/package.json` and `ui/package.json`. It would be nice to automate this process as it can be easy to forget something.

This should probably include an update to RELEASE.md to reflect the changes.

**Comment by cristinadresch** [comment]
this will be fixed by upgrading yarn
