### ISSUE TITLE
Visual Design: Cloud init user data snippet

### ISSUE THREAD

**Issue by amylily1011** [canonical-web-and-design/maas-ui#1260]
After discussing with the Core team, this is the adjusted version.
From: https://github.com/canonical-web-and-design/MAAS-squad/issues/1941

Iteration 4 Design: https://zpl.io/beEMjLW

@lyubomir-popov let's work together on this one :-)

**Comment by lyubomir-popov** [comment]
https://app.zeplin.io/project/5ee104736f620ab91f8c5c97/dashboard?seid=5eece4d66703a929311944a0
