### ISSUE TITLE
Add chassis suggests power types which aren't chassis

### ISSUE THREAD

**Issue by Caleb-Ellis** [canonical-web-and-design/maas-ui#1285]
https://bugs.launchpad.net/maas/+bug/1883743

MAAS version: 2.8.0~rc5 (8551-g.d0d4cdf79)
@maas-ui/maas-ui 1.3.3 (6c3f901).

1. From machine listing, click Add Hardware
2. Select Chassis
3. Note the prompt for power type lists many power types
4. Select LXD (or IPMI)
5. Fill in the necessary details with valid nonsense
6. Click "Save Chassis"

Get an error!

Error:Invalid chassis_type: Value must be one of: mscm; msftocs; powerkvm; recs_box; seamicro15k; ucsm; virsh; vmware (not 'lxd')

The UI should filter to the known list, in absence of https://bugs.launchpad.net/maas/+bug/1876855

We should reinstate the hardcoded list of chassis types in the 2.8 branch to be released in 2.8.1, and use the updated api from https://bugs.launchpad.net/maas/+bug/1876855 in master

**Comment by anthonydillon** [comment]
@Caleb-Ellis do you mind taking a look into this one.

**Comment by Caleb-Ellis** [comment]
@anthonydillon yeah no worries
