### ISSUE TITLE
Updating controller name shouldn't be allowed in the UI

### ISSUE THREAD

**Issue by Caleb-Ellis** [canonical-web-and-design/maas-ui#1289]
https://bugs.launchpad.net/maas/+bug/1871605

MAAS doesn't really support updating hostname for a controller.

The UI currently allows it but the change has no effect, the result returned by the controller.update websocket call still has the previous hostname.

We shouldn't let users change hostname for the controller.

**Comment by Caleb-Ellis** [comment]
We should probably only make changing name possible for machines and devices, not controllers or pods.

**Comment by huwshimi** [comment]
This is fixed in the React header.
