### ISSUE TITLE
Errors when deleting users are not dispatched

### ISSUE THREAD

**Issue by huwshimi** [canonical-web-and-design/maas-ui#129]
The websocket messages are:
`{"method":"user.delete","type":0,"params":{"id":2},"request_id":2}` and `{"type": 1, "request_id": 2, "rtype": 1, "error": "(\"Cannot delete some instances of model 'User' be...`.

For some reason a `DELETE_USERS_ERRORS` is not dispatched with that error.

**Comment by squidsoup** [comment]
PR: https://github.com/canonical-web-and-design/maas-ui/issues/129
