### ISSUE TITLE
Unable to view storage tab on controllers detail page

### ISSUE THREAD

**Issue by Caleb-Ellis** [canonical-web-and-design/maas-ui#1290]
https://bugs.launchpad.net/maas/+bug/1874356

In the UI the Storage tab is hidden if the controller is in "New" status. We should remove that conditional because it's dumb.

**Comment by sparkiegeek** [comment]
@Caleb-Ellis can you confirm what happened here, was this fixed? if so can you link a commit? I'm trying to update the state of the LP bug and ascertain if this was fixed in 2.9

**Comment by Caleb-Ellis** [comment]
@sparkiegeek that's odd - it's not fixed, so I'm not sure why I closed the issue originally. Reopening.

**Comment by Caleb-Ellis** [comment]
@sparkiegeek it's fixed for real now, in [master](https://github.com/canonical-web-and-design/maas-ui/commit/009fb342bd2d04aa4fe479edc91bcc9b7c710f7f) and [2.9](https://github.com/canonical-web-and-design/maas-ui/commit/f23264c346ab3c32e9adab886cd591ae43adf421)
