### ISSUE TITLE
Update dir structure for models

### ISSUE THREAD

**Issue by huwshimi** [canonical-web-and-design/maas-ui#1309]
To tame the sprawl of files for each model the directory structure could be updated to combine all the files related to a particular model.

Existing structure:

base/
- actions/
-- dhcpsnippet/...
- reducers/
-- dhcpsnippet/...
- selectors/
-- dhcpsnippet/...
- types.ts
- proptypes.ts
- constants.ts

Proposed structure:

models/
- dhcsnippet/
-- actions.ts
-- reducers.ts
-- selectors.ts
-- types.ts
-- [proptypes.ts]
-- [constants.ts]

Is it OK for these files to include code that is only used by specific parts of the UI? E.g. the machine action/reducer/selector that sets the selected state for the machine list, or a selector that is specific to a piece of UI.

Are there any actions/reducers/selectors that aren't connected to a model? Would they still live in base/actions/... etc.?

**Comment by Caleb-Ellis** [comment]
> Is it OK for these files to include code that is only used by specific parts of the UI? E.g. the machine action/reducer/selector that sets the selected state for the machine list, or a selector that is specific to a piece of UI.

I think that's fine. When I think about it in terms of looking for a particular action/reducer/selector I think it makes sense for them to all be in the same place, tied to the model.

> Are there any actions/reducers/selectors that aren't connected to a model? Would they still live in base/actions/... etc.?

I guess the websocket files. Maybe the common utils? There's also the auth files which are a bit of a special case, but they're a sort of subtype of user. Possible that hooks could live in base too.

**Comment by huwshimi** [comment]
Closing this as there are issues for each of the remaining models to transition to slices.
