### ISSUE TITLE
The Usabilla script always included

### ISSUE THREAD

**Issue by huwshimi** [canonical-web-and-design/maas-ui#1312]
The Usabilla script in the footer does not check for the `enable_analytics` option. Presumably it should?

**Comment by huwshimi** [comment]
It doesn't look like it used to have the check: https://git.launchpad.net/~huwshimi/maas/tree/src/maasserver/templates/maasserver/footer.html?h=migrate-tests-to-jest#n20

**Comment by squidsoup** [comment]
@huwshimi I would think so yeah.

**Comment by huwshimi** [comment]
Fixed by: https://github.com/canonical-web-and-design/maas-ui/pull/1431
