### ISSUE TITLE
Inconsistent deployment for 20.04 and 18.04

### ISSUE THREAD

**Issue by amylily1011** [canonical-web-and-design/maas-ui#1321]
When deploying 20.04 LTS "Focal Fossa"  and have "Register as KVM host" checked, the details page shows that it is deploying 18.04 LTS "Bionic Beaver" instead.

There is no error message on the KVM host check box and the check box is not disabled when other OS (aside from 18.04 LTS) was selected.

![Image](https://discourse.maas.io/uploads/default/original/1X/6c076d3257249a51cca262331cb025ac0eaf60df.png)
![Image](https://discourse.maas.io/uploads/default/original/1X/a43fba4b54f351ddbe01f69a3075b2ee476ef287.png)

**Comment by Caleb-Ellis** [comment]
Aahhhh we need to update legacy machine details to follow the same pattern as the new machine list. :(

**Comment by gianlucagiacometti** [comment]
I can't check the "Register as MAAS KVM Host" if I choose Ubuntu 20.04, the checkbox is disabled. It comes up only if I select Ubuntu 10.04
My Maas version is the latest 2.0.0 stable

![immagine](https://user-images.githubusercontent.com/52405/86510486-4d9a9b00-bdf0-11ea-9f82-0159adde0357.png)

**Comment by Caleb-Ellis** [comment]
This has been fixed for 2.9 and should be included in the next 2.8 release.
