### ISSUE TITLE
After "mark bloken" and "mark fixed" it's no more possible to mark the machine broken again

### ISSUE THREAD

**Issue by gianlucagiacometti** [canonical-web-and-design/maas-ui#1369]
**Describe the bug**
After "mark bloken" and "mark fixed" it's no more possible to mark the machine broken again. At the same time the status of the machine after fixing does not come back to its original name (i.e. Ubuntu 18.04), but it becomes "Deployed".

**MAAS version**
2.8.1

**To Reproduce**
1. Mark a machine broken
2. Mark it fixed
3. The Status changes to "Deployed"
4. Mark Broken does not appear anymore in the dropdown list

**Expected behavior**
It should be possible to re-iterate the mark broken - mark fixed as many times as needed.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox
 - Version 78.0.1

**Comment by squidsoup** [comment]
Hi @gianlucagiacometti, thank you for reporting this bug. As it is a server issue, I've moved the bug to Launchpad. If you'd like to track the progress of the bug on Launchpad, you'll need to create an account, and then you can select "This bug affects you" to track the bug.

![image](https://user-images.githubusercontent.com/130286/88500751-b0f9a080-d01d-11ea-8a76-1a10ff11c840.png)

**Comment by squidsoup** [comment]
Closing in favour of https://bugs.launchpad.net/maas/+bug/1889026
