### ISSUE TITLE
Unclickable blue link "See all events"

### ISSUE THREAD

**Issue by amylily1011** [canonical-web-and-design/maas-ui#1372]
"See all events" blue link is not clickable.

I tried to click the blue link "See all events" on the machine details page (on the error message), but it didn't link me anywhere. 

![Screen Shot 2020-07-09 at 2.14.04 PM.png](https://images.zenhubusercontent.com/5e6628e0ff9a3ccb84677b2f/16bc7cff-5bdb-4abe-bcbe-84280a2e851b)

**Comment by squidsoup** [comment]
@amylily1011 if you're able to reproduce this, could you please tell us what the URL for "See all events" is?

**Comment by amylily1011** [comment]
@squidsoup I wasn't able to reproduce this at the moment. 😄  I think I found this bug when there were still fake machines on bolla and now that bolla was reset (by Adam last week), all machines seem to work. I'll put this on hold for now until I found this again and will make sure I include the url for it :-).

**Comment by huwshimi** [comment]
These tabs weren't loading when the url changed. I fixed this in this PR: https://github.com/canonical-web-and-design/maas-ui/pull/1626.

There is another issue where the links go to machines instead of controllers: https://github.com/canonical-web-and-design/maas-ui/issues/1773.
