### ISSUE TITLE
Terrible user experience adding existing LXD host

### ISSUE THREAD

**Issue by amylily1011** [canonical-web-and-design/maas-ui#1375]
I wanted to test the LXD VM host feature again, so I added a KVM host through MAAS.

It properly connected to the system and promptly imported all my existing VMs (why???).
It then marked any VM that it didn't already know about as Commissioning which got me greatly concerned as those are pre-existing production VMs that I absolutely don't want MAAS to go and reboot right now.

I resorted to blocking network access from MAAS to that LXD host to avoid any additional issue with this. Then when deleting the KVM host, the UI made me feel like it may want to go and delete all my existing VMs as well. Obviously it couldn't and it may never have tried doing that (I don't know).

One last issue is that as mentioned some VMs on that host were already individually added to MAAS as machines. Looks like MAAS somehow merged that information and so when removing the LXD host from MAAS, it promptly deleted 12 of my machines which I now have to go and manually re-add, commission and re-configure.

This whole behavior seems completely unacceptable to me. Either MAAS can deal with existing VMs and add them as running, properly handling the case where some of the VM names may already be defined in MAAS, or it can only deal with an empty LXD host and should immediately refuse to connect should anything already exist there.

The MAAS behavior when deleting a LXD host from MAAS should also be clarified so that users are not left wondering if MAAS is about to go on a deleting spree potentially causing massive data loss.

Obviously all of this would be made significantly easier and safer if MAAS would support LXD projects since it could then just always require an empty project avoiding this entire mess.

Just to be clear, the behavior I would have expected there would be one of:
 - MAAS to ignore all existing VMs and just let me create more new VMs
 - MAAS to tell me that there are existing VMs and allow me to pick those that I want to see imported as machines
 - MAAS to tell me that it can't deal with LXD hosts that have existing VMs

**Comment by squidsoup** [comment]
@amylily1011 is the a bug from launchpad?

**Comment by amylily1011** [comment]
@squidsoup, yes 😄 , I scheduled a call with Stephane (LXD) next week as he filed this bug and I might need to understand if design changes is needed and if we can fit it in 2.9.

**Comment by squidsoup** [comment]
The concerning behaviour he's describing isn't a UI issue (although there may be UI changes that fall out of it). More discussion is definitely needed, but I'm not sure this makes sense as a bug filed against the UI.

**Comment by amylily1011** [comment]
The new tag (needs info) makes perfect sense! Thanks for grooming this @squidsoup.

**Comment by amylily1011** [comment]
After taking to Stephane: https://docs.google.com/document/d/1C3p1RiXK0TvNe1mOtXH1We2rsOk7W2PsA-Whrs0i0_c/edit?usp=sharing

**Comment by amylily1011** [comment]
@cristinadresch I think we can close this, because this is directly related to that feature.
