### ISSUE TITLE
Add machine does not show all supported option

### ISSUE THREAD

**Issue by squidsoup** [canonical-web-and-design/maas-ui#1398]
I was helping a customer setup MAAS and I realized that a number of options available on the API when adding a new machine are missing from the UI. Options that are missing include whether commissioning runs, what custom commissioning scripts run, and whether the BMC is configured. I believe these were omitted due to space, I'm creating this bug to revisit that decision since we are adding collapsible options to deploying.

Missing options:

 :param commission: Optional. Request
the newly created machine to be created with status set to
COMMISSIONING. Machines will wait for COMMISSIONING results and not
time out.
:type commission: Boolean

:param enable_ssh: Optional. Whether to enable SSH for
the commissioning environment using the user's SSH key(s). '1' == True,
'0' == False.
:type enable_ssh: Int

 :param skip_bmc_config: Optional. Whether to skip
re-configuration of the BMC for IPMI based machines. '1' == True, '0'
== False.
:type skip_bmc_config: Int

 :param commissioning_scripts: Optional. A comma
seperated list of commissioning script names and tags to be run. By
default all custom commissioning scripts are run. Built-in
commissioning scripts always run. Selecting 'update_firmware' or
'configure_hba' will run firmware updates or configure HBA's on
matching machines.
:type commissioning_scripts: String

 :param testing_scripts: Optional. A comma seperated
list of testing script names and tags to be run. By default all tests
tagged 'commissioning' will be run. Set to 'none' to disable running
tests.
:type testing_scripts: String

 :param description: Optional. A optional description.
:type description: String

[LP#1887699](https://bugs.launchpad.net/maas/+bug/1887699)

**Comment by squidsoup** [comment]
Hi @amylily1011, this is a potential enhancement for the add machine form, that will need design consideration (possibly for next cycle)?

**Comment by amylily1011** [comment]
Sounds great! :-) We should keep this in mind in the planning loop.

**Comment by huwshimi** [comment]
Closing as the implementation has an issue here: https://github.com/canonical-web-and-design/maas-ui/issues/1884
