### ISSUE TITLE
No item with pk

### ISSUE THREAD

**Issue by squidsoup** [canonical-web-and-design/maas-ui#1400]
https://sentry.is.canonical.com/canonical/maas-ui/issues/10558/?referrer=github_plugin

```
Error: Possibly unhandled rejection: No item with pk: 6wrhq4

Possibly unhandled rejection: No item with pk: 6wrhq4
```

**Comment by huwshimi** [comment]
To reproduce:
- Visit a machine e.g. /MAAS/l/machine/76pa3f
- Open the same machine in a new tab and delete it
- Stop the server
- Wait a few seconds and start it again
- When the ws reconnects again you should see the error in the first tab

**Comment by anthonydillon** [comment]
Can you estimate this please.
