### ISSUE TITLE
Wrong steps provided to add a rack controller

### ISSUE THREAD

**Issue by sombrafam** [canonical-web-and-design/maas-ui#1416]
Originally reported at:
  https://bugs.launchpad.net/bugs/1888002

Ubuntu Series: Focal
MAAS Version: 2.8.1 (snap)

In the MAAS interface when I try to install a new rack controller, it shows the following message:

# To add a new rack controller, SSH into the rack controller.
# Install the maas-rack-controller package.
sudo apt install maas-rack-controller
# Register the rack controller with this MAAS. If the rack controller (and machines)
# don't have access to the URL, use a different IP address to allow connection.
sudo maas-rack register --url http://localhost:5240/MAAS --secret 13bdcd78351ca3edf75d67e673a43f06"

This message should not be displayed or should be updated as the maas-rack command is not
present in the snap version command. The correct command to register a rack controller is:

sudo maas init rack

Not sure if this is the same for the package version.

**Comment by squidsoup** [comment]
Fixed by #1364
