### ISSUE TITLE
Functional VLAN tagged bonding interfaces are shown as disconnected 

### ISSUE THREAD

**Issue by casual-lemon** [canonical-web-and-design/maas-ui#1429]
**Describe the bug**
After configuring bond and VLAN tagged interfaces and deploying the server,
VLAN interfaces which are functional, are still shown as disconnected in MAAS UI.

**maas-ui version**
2.7.2 (8284-g.037e34a46)
2.8

**MAAS version**
snap info maas
snap-id: shY22YTZ3RhJJDOj0MfmShTNZTEb1Jiq
tracking: 2.7/stable

**LP issue**
lp#1881901 https://bugs.launchpad.net/maas/+bug/1881901 

**To Reproduce**

**setup new maas network connection to local vm**  
---- 
in KVM/virt-manager

1.  Edit
2.  New Connection
3.  Click + at bottom of screen
4.  Add new name (maas-network)
5.  Uncheck "Enable DHCPv4"
6.  Assign a valid network range (192.168.100.0/24)
7.  Finish & Apply

------
**create new PXE boot VM **
1. Click create new VM from VM manager on laptop
2. Check Network Boot(PXE)
3. Connection choose from drop down the new network we just created (QEMU/KVM: 10.230.56.78)
4. Finish wizard with defaults or add more memory/disk space if you choose
5. Click blue icon (i) to show information on VM
  - Add Hardware
  - Add 2 more NICs to prep for bonding
  - Use defaults & Save/Close 
-------
1. Login to new MAAS at assigned ip address from maas with credentials you set up ex: http://10.230.56.78:5240/MAAS
2. Add any missing ssh keys under your user-> SSH keys
3. Add newly created machine 
 - Power type -> Virsh 
  - Address: qemu+ssh://ubuntu@10.230.56.78/system
  - Virsh VM ID: matches what you called the VM you just created
  - I had to add a password or it wouldn't been able to power on
  - Add Mac address of new VM
4. Select New machine 
5. Select Network
6. Add 2 Interfaces
 - Select Button "Create Bond"
 - Use defaults & Save
7. Checkbox the bond you just created
  - From drop down select "Add alias or VLAN"
  - Under Type Select "VLAN"
  - Select Add    
7. You should now see a disconnect icon under Link/Interface speed column 

**Expected Behavior**
The icon for disconnect under Link/Interface speed column, should not appear because bonds and VLANs are examples of software devices that do not exist outside the scope of the deployed system, and therefore cannot have a specific connected or disconnected state

**Screenshots**
![Screenshot from 2020-07-29 14-25-12](https://user-images.githubusercontent.com/62671519/88849631-63a93a80-d1a7-11ea-9944-8f7377a36387.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04 
 - Browser Firefox
 - Version 78.0.2 (64-bit)

**Additional context**
1. We could hide the icon for that condition
2. Add missing VLAN logic to be included in the node details table

**Comment by sparkiegeek** [comment]
@Caleb-Ellis this also needs backporting to 2.8 too please

**Comment by Caleb-Ellis** [comment]
@sparkiegeek whoops, done!

https://github.com/canonical-web-and-design/maas-ui/commit/edc9dd0912e2eb6dbe70deee5dd88a6b11000843
