### ISSUE TITLE
KVM list popover design

### ISSUE THREAD

**Issue by lyubomir-popov** [canonical-web-and-design/maas-ui#1432]
Provide mockups for how the storage popovers implemented [here ](https://github.com/canonical-web-and-design/maas-ui/pull/1422) should look.

https://user-images.githubusercontent.com/25733845/88891743-0389c580-d287-11ea-9b8d-9d1e49b3932f.png

**Comment by lyubomir-popov** [comment]
![Uploading image.png…]()

**Comment by lyubomir-popov** [comment]
@Caleb-Ellis @amylily1011 design proposal here: 
https://zpl.io/V4WvJ80

**Comment by amylily1011** [comment]
LGTM :shipit:

**Comment by Caleb-Ellis** [comment]
@lyubomir-popov Sorry I forgot to mention that the old storage popover showed multiple pools (if more than 1 existed). I would say that 1-3 is likely, 4+ is much less likely.

**Comment by lyubomir-popov** [comment]
@caleb I've updated it to be the same as the storage selector minus the request part. This way it takes less vertical space. So essentially a pixel-perfect version of your original design :)
