### ISSUE TITLE
MAAS fails to start image download, can't "Continue"

### ISSUE THREAD

**Issue by anthonydillon** [canonical-web-and-design/maas-ui#1462]
Bug originally filed: https://bugs.launchpad.net/bugs/1862678

When installing snap 2.7.0~rc6 (8229-g.fa71c492d) on Ubuntu 19.10, can't get past the configuration journey. 

Installation was attempted right after removing older snap of MAAS with "sudo snap remove maas" (notice "--purge" was omitted in that remove command).  Entire sequence was:

1. sudo snap remove maas
2. sudo snap install --channel=2.7/candidate maas
3. sudo maas init --mode all
4. accept default URL
5. set admin user to "admin"
6. set admin password to "admin" and confirm
7. set email to "admin@admin.com"
8. set key to personal launchpad key with "lp:billwear"
9. bring up default URL
10. login as admin, password admin
11. enter "8.8.8.8" in DNS block
12. The bottom UI block, entitled "Ubuntu", has 18.04 image selected but selected radio button grayed out.
13. "STATUS" for release 18.04 is "Selected for download." 
14. "Update selection" is clickable.
15. "Continue" is not clickable.  
16. Selecting "Update selection" without changing any checkboxes above results in "Update selection" grayed out, with a visual indication that MAAS is working (spinning cursor, maybe?).
17. "Update selection" remained grayed out indefinitely (does not seem to complete).

Closing and restarting MAAS tab brings user back to same screen with only two differences:

18. "Update selection" is clickable again.
19. MAAS does not show an indication that it is working.

Logjam was broken by:
20. selecting another OS from the checkboxes (in this case, 16.04)
21. Choosing "Update selection"

The screen begins to work as expected, which is that:
22. "Continue" is enabled
23. First OS choice (18.04, selected by default) begins to download.
24. Second OS choice downloads when first is complete.
25. OSes sync with rack controller.
26. "Continue" proceeds to the next screen.

Repeated operation by doing:

27. sudo snap stop maas
28. sudo snap remove --purge maas
29. sudo maas init --mode all
30. accept default URL
31. set admin user to "admin"
32. set admin password to "admin" and confirm
33. set email to "admin@admin.com"
34. set key to personal launchpad key with "lp:billwear"
35. bring up default URL
36. login as admin, password admin
37. enter "8.8.8.8" in DNS block
38. The bottom UI block, entitled "Ubuntu", has 18.04 image selected with active radio button.
39. "Continue" is enabled
40  MAAS immediately begins downloading 18.04 image.
41. "Continue" takes MAAS to expected next screen.

Repeated steps 1-11 (snap remove without --purge option), but Image loading screen works normally.  Did not take a screenshot before breaking the logjam by choosing a second OS (see steps 20-21). 

Contents of /var/snap/maas/common/log attached as maaslogs.tar.gz.

**Comment by squidsoup** [comment]
I'm unable to reproduce this on 2.7/stable on focal. Clicking "update selection" can take a while, but it does eventually resolve to "selection updated", and the continue button is enabled.

![image.png](https://images.zenhubusercontent.com/5b15b1fca281cf5395ef819b/39baa8fc-b947-4acf-8fd6-da0379112c60)
