### ISSUE TITLE
 Cannot select user uploaded commissioning scripts 

### ISSUE THREAD

**Issue by casual-lemon** [canonical-web-and-design/maas-ui#1477]
**Describe the bug**
 Cannot select user uploaded commissioning scripts 

**maas-ui version**
snap stable 2.8 
MAAS version: 2.8.1 (8567-g.c4825ca06)

**MAAS version**
MAAS 2.8 stable

**LP issue**
lp#[1891924](https://bugs.launchpad.net/maas/+bug/1891924)

**To Reproduce**
After uploading custom user commissioning scripts.
- Settings -> Commissioning Scripts -> Upload script. (choose any .sh script to upload)'
 - ensure upload successful
- Go back to the Machines tab.
- Select the machine to commission
- Under Take Action -> Click Commission
- You should see the commissioning script you just uploaded.
- Click the X button to remove it from the list
- Try to add it back in and it fails with this error: looking in the dev console log
```
TypeError: $scope.onParameterChange is not a function
    onTagRemoved 1.655e38a7cfa27fc32943.js:35909
    fn 1.655e38a7cfa27fc32943.js line 11536 > Function:4
    scopeName 1.655e38a7cfa27fc32943.js:9346
    handleUndefinedResult 1.655e38a7cfa27fc32943.js:27112
    trigger 1.655e38a7cfa27fc32943.js:27112
    trigger
```
Attached is a video showing steps to reproduce error.

**Expected behavior**
User is allowed to select commissioning scripts

**Screenshots**
![Screenshot from 2020-08-17 12-24-47](https://user-images.githubusercontent.com/62671519/90430451-afebea00-e084-11ea-926c-fbffe660fc8f.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Browser: Firefox 
 - Version: 79.0

**Additional context**

[commissiongscriptspart2-2020-08-17_11.43.zip](https://github.com/canonical-web-and-design/maas-ui/files/5086114/commissiongscriptspart2-2020-08-17_11.43.zip)

**Comment by casual-lemon** [comment]
This issue exists in MAAS 2.7 as well.

**Comment by anthonydillon** [comment]
@casual-lemon thank you very much for taking the time to report this issue to us.

**Comment by casual-lemon** [comment]
Will this being going into 2.7 branch as well?
Also, FYI I noticed when on 2.7.3, I was not allowed to upload any .sh files under Settings -> Commissioning Scripts -> Upload a Script 
Thank you!

**Comment by squidsoup** [comment]
Re-opening, as this requires backporting to 2.7 and 2.8.

**Comment by Caleb-Ellis** [comment]
@squidsoup re: being unable to upload .sh files - wasn't that a weirdly specific Linux/Firefox bug? Do you remember if that was backported to 2.7/2.8?

**Comment by squidsoup** [comment]
> @squidsoup re: being unable to upload .sh files - wasn't that a weirdly specific Linux/Firefox bug? Do you remember if that was backported to 2.7/2.8?

I think you're probably referring to [this issue](https://github.com/canonical-web-and-design/maas-ui/commit/edc35942801b568d8c47c5da17d7c46126f1c8f1)? That was definitely backported.
