### ISSUE TITLE
Builtin commissioning scripts should be unable to be deselected in the UI

### ISSUE THREAD

**Issue by squidsoup** [canonical-web-and-design/maas-ui#1490]
**Describe the bug**
fe5acf1 migrated commissioning scripts into the database. They are now handled the same way testing scripts are. This results in all commissioning scripts being shown when selecting commissioning. I think this is a good thing as the user now knows exactly what is being run. I do think the UI needs two few minor changes to accommodate this.

1. The title should be changed from "Additional commissioning scripts" to just "Commissioning scripts" I'd suggest changing "tests" to "Testing scripts" as well to keep wording uniform.
2. Commissioning scripts which has default=True and is NOT tagged noauto should always be selected. These scripts will be selected by the backend even if the user deselects them.

**maas-ui version**
master

**MAAS version**
all

**LP issue**
https://bugs.launchpad.net/maas/+bug/1892238

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by amylily1011** [comment]
Based on #1488  this makes sense (I wasn't able to see it in Bolla, but the disabled version makes sense.) We have a concept of chips in juju, for the search and filter. https://vanillaframework.io/docs/patterns/chip
We can use this component to make the distinction between each script as well.
