### ISSUE TITLE
Hacking.md does not explain how to set up bare minimum locally to then connect to bola

### ISSUE THREAD

**Issue by lyubomir-popov** [canonical-web-and-design/maas-ui#1493]
[hacking.md](https://github.com/canonical-web-and-design/maas-ui/blob/master/HACKING.md#edit-local-config) does not tell me how to install the bare minimum locally in multipass, so I can then connect to bolla.

**Comment by squidsoup** [comment]
Hey @lyubomir-popov, if you're connecting to bolla, you don't need to set anything up in multipass, you should just be able to use `./run`.
