### ISSUE TITLE
Update new release notification design

### ISSUE THREAD

**Issue by huwshimi** [canonical-web-and-design/maas-ui#1507]
Update the new release notification to remove the opt-out menu.

<img width="936" alt="Screen Shot 2020-08-25 at 9 47 55 am" src="https://user-images.githubusercontent.com/361637/91107502-cb747780-e6b8-11ea-9360-7654105f3258.png">

**Comment by anthonydillon** [comment]
@huwshimi what is this blocked on.

**Comment by huwshimi** [comment]
> @huwshimi what is this blocked on.

Oops, I think it was blocked on design feedback, but you replied straight away :).
