### ISSUE TITLE
Doughnut 🍩 charts clobber text

### ISSUE THREAD

**Issue by sparkiegeek** [canonical-web-and-design/maas-ui#1588]
**Describe the bug**
On the new KVM details page with 🍩 charts, the 🍩 chart overlaps the text in the table.

**maas-ui version**

maas-ui/maas-ui 1.3.1 (83bd057f).

**MAAS version**
MAAS version: 2.9.0~alpha1 (8845-g.9d0510ee5)

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to http://bolla.internal:5240/MAAS/r/kvm/190 
2. See overlap

**Expected behaviour**
Doughnut chart doesn't elide the table

**Screenshots**
![image](https://user-images.githubusercontent.com/246192/91545490-0674e600-e919-11ea-993b-db0916e6f661.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04 LTS
 - Browser Firefox
 - Version 80
 - Screen resolution: 2560x1440

**Additional context**

**Comment by huwshimi** [comment]
@sparkiegeek I'm not able to reproduce this today, is it still appearing like that for you?

**Comment by sparkiegeek** [comment]
> @sparkiegeek I'm not able to reproduce this today, is it still appearing like that for you?

Yes

**Comment by sparkiegeek** [comment]
Seems to be :fire: :fox_face: only, can't reproduce it in Chrome
