### ISSUE TITLE
Improve responsiveness of KVMDetails machine list dropdowns

### ISSUE THREAD

**Issue by Caleb-Ellis** [canonical-web-and-design/maas-ui#1590]
Improvements:
- [x] Dropdown position. It would be nice if ContextualMenu could be given `position="auto"` where the dropdown position would depend on the horizontal position of the toggle.
- [x] Responsive dropdown size. The overall width of the dropdown should look good on all screen sizes.
- [x] Responsive column widths. If we can pass a className to MachineListTable we should be able to give it custom column widths.

**Comment by cassiocassio** [comment]
@lyubomir-popov Is this an interesting general problem or no? Where else in e.g. Vanilla table patterns, should we plan for children to know the width of their parent like this?

**Comment by lyubomir-popov** [comment]
I don't think children need to know the width of the parent, that sounds counterintuitive to me. Usually it's up to the parent container to determine the layout and space allocated to each child. 

All the children can do is define a min/max-width beyond which the data displayed can't fit.

The third checkbox is exactly how I imagine this working - a responsive behaviour that is supplied on demand once the exact content is known.
