### ISSUE TITLE
Bad routing from Angular to React for user settings

### ISSUE THREAD

**Issue by sparkiegeek** [canonical-web-and-design/maas-ui#1598]
**Describe the bug**
From a legacy page, e.g. http://bolla.internal:5240/MAAS/l/devices but also machine details and others, clicking on your username ends up trying to request `http://bolla.internal:5240/MAAS/r/account,prefs` which is a **404** (note the `,` instead of a `/`)

**maas-ui version**
`c6354d6e` (master) but also `d82bf295` from 2.8 branch

**MAAS version**
> MAAS version: 2.9.0~alpha1 (8858-g.1c1da13c5)

 but also 
> MAAS version: 2.8.2 (8577-g.a3e674063)

**LP issue**
No

**To Reproduce**
1. Go to '/l/devices'
2. Click on your username (top right)
3. See 404

**Expected behavior**

Navigate to `/r/account/prefs`

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04 LTS
 - Browser Firefox
 - Version 80.0

**Additional context**

**Comment by squidsoup** [comment]
Interesting bug, I can reproduce it, but not consistently!

**Comment by huwshimi** [comment]
I can reproduce by going to any React page (Machines, KVM, Settings, but not prefs) then going to any legacy page then clicking on prefs.
