### ISSUE TITLE
Unable to upload script "sd350v434.sh"

### ISSUE THREAD

**Issue by anthonydillon** [canonical-web-and-design/maas-ui#1600]
**Describe the bug**
The description of the issue can be found on discourse:
https://discourse.maas.io/t/unable-to-upload-script/2232

**maas-ui version**
Unknown

**MAAS version**
Unknown

**LP issue**
None

**To Reproduce**
I am unable to reproduce. I have uploaded a testing script with the same name which works. I wonder if its the contents or a different error being reported as a naming issue in the UI?

**Comment by squidsoup** [comment]
@anthonydillon I wanted to reply on discourse, but the thread is locked. This is a message from the server - it isn't complaining about the filename, but the name of the script in the file contents/metadata.

**Comment by anthonydillon** [comment]
Ah so there is a reference to the filename in the script itself? I think the error message could be improved.

**Comment by squidsoup** [comment]
> Ah so there is a reference to the filename in the script itself? I think the error message could be improved.

Not the filename, but the name of the script in the metadata header: 

https://maas.io/docs/commissioning-and-hardware-testing-scripts

The error message comes from the server, so we'd need to open a but on LP.

**Comment by anthonydillon** [comment]
Yeah, I think we should. If you don't mind?
