### ISSUE TITLE
Admin user is unable to change other users' password

### ISSUE THREAD

**Issue by vtapia** [canonical-web-and-design/maas-ui#1615]
**Description**
From the users page (http://$HOST:5240/MAAS/r/settings/users), editing a user and setting a new password does not update its value.

**MAAS version**
2.8.2-8577-g.a3e674063-0ubuntu1
2.7.3-8291-g.384e521e6-0ubuntu1

**LP issue**
lp#1894727

**To Reproduce**
1. As an admin, login to UI
2. Create user
3. Update user's password
4. Try to login with the user+new password

**Expected behavior**
Password should be updated

**Additional context**
Logging in with the user and updating its own password does work (it does update the db entry). I've noticed that the details form triggers authActions.changePassword() while the user form does not.

**Comment by cristinadresch** [comment]
Closing bc it's a backend issue

**Comment by cristinadresch** [comment]
Reopening, this needs to be worked on for 2.9

**Comment by sparkiegeek** [comment]
Needs backporting to 2.7 and 2.8

**Comment by huwshimi** [comment]
This is now backported to [2.7](https://github.com/canonical-web-and-design/maas-ui/pull/2241) and [2.8](https://github.com/canonical-web-and-design/maas-ui/pull/2238).
