### ISSUE TITLE
Not obvious why there are no numa nodes

### ISSUE THREAD

**Issue by huwshimi** [canonical-web-and-design/maas-ui#1709]
When toggling "view by numa nodes" and there are no nodes it isn't obvious why. It's possible we just need to update the toggle to be hidden when the list of numa nodes is empty.

<img width="956" alt="Screen Shot 2020-09-28 at 4 09 43 pm" src="https://user-images.githubusercontent.com/361637/94397168-9c18c500-01a6-11eb-9a05-f6fbd5a17b37.png">

**Comment by Caleb-Ellis** [comment]
Fixed in #1725
