### ISSUE TITLE
Mark broken doesn't prompt for reason when intitated from machine details

### ISSUE THREAD

**Issue by sparkiegeek** [canonical-web-and-design/maas-ui#1726]
**Describe the bug**
When taking an action from the machine details page, to mark machines as broken the UI doesn't prompt for an explanation (unlike the machine listing - implemented in #1663 )

**maas-ui version**
`@maas-ui/maas-ui 1.3.1 (349bba46)`

**MAAS version**
master

**LP issue**
No

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to an acquired machine's detail page
2. Click on ''Take Action"
3. Scroll down to 'Mark broken'
4. See lack of text box for the error description

**Expected behaviour**
Text box for adding error description.

**Screenshots**
![image](https://user-images.githubusercontent.com/246192/94918300-2ebcab00-04aa-11eb-9e8d-5c35aa748cba.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04 LTS
 - Browser: Firefox
 - Version: 81

**Additional context**

**Comment by cristinadresch** [comment]
@squidsoup can we look into this one? high priority, if you could give an update here to keep adam in the loop would be great. Not sure if we should start an epic with things to fix for 2.9 or we decided to do that only when the first RC goes out? 

cc @huwshimi @Caleb-Ellis
