### ISSUE TITLE
Machine list message link has # in it

### ISSUE THREAD

**Issue by huwshimi** [canonical-web-and-design/maas-ui#1774]
**Describe the bug**
On the machine list if you get a message about "One rack controller is not yet connected to the region. Visit the rack controllers page for more information." there is a link to http://192.168.1.52:5240/MAAS/#/controllers

<img width="921" alt="Screen Shot 2020-10-19 at 12 37 54 pm" src="https://user-images.githubusercontent.com/361637/96392841-069ead00-1209-11eb-8dd3-384bada2cb53.png">

**Comment by squidsoup** [comment]
Proposed on LP https://code.launchpad.net/~blr/maas/+git/maas/+merge/392431
