### ISSUE TITLE
UI navigation bar glitch showing Hardware drop down on wide screen

### ISSUE THREAD

**Issue by anthonydillon** [canonical-web-and-design/maas-ui#1799]
On a wide screen (2560px) the UI when viewing legacy pages (e.g. http://bolla.internal:5240/MAAS/l/devices) the main navigation bar shows a [Hardware \/ ] [Machines] [Devices] [Controllers] [KVM] etc.

The Hardware menu duplicates the Machines, Devices, Controllers, KVM entries.

It is *not* reproducible on the React pages e.g. http://bolla.internal:5240/MAAS/r/machines/

I have force reloaded my browser several times, and have no zoom or other changes.

MAAS version: 2.9.0~beta6 (9063-g.cb228c79c)
MAAS UI: @maas-ui/maas-ui 1.3.1 (e2e8847a).

Firefox 81.0.2 on Ubuntu 20.04 LTS

**Comment by sparkiegeek** [comment]
Note in the console i see an invalid media value

From DevTools I then see `@media (max-width:#111) {` which is obviously wrong - #111 is a colour :/

**Comment by sparkiegeek** [comment]
Oh - https://github.com/canonical-web-and-design/maas-ui/pull/1798

**Comment by anthonydillon** [comment]
> From DevTools I then see @media (max-width:#111) { which is obviously wrong - #111 is a colour disappointed

This is [an issue in Vanilla](https://github.com/canonical-web-and-design/vanilla-framework/issues/3371). Once fixed there this fix will find its way to MAAS in due course.
