### ISSUE TITLE
Logging out with external auth configured intermittently errors

### ISSUE THREAD

**Issue by squidsoup** [canonical-web-and-design/maas-ui#1802]
**Describe the bug**
Logging out with external auth configured (using RBAC), can result in the error "maximum call stack exceeded". This error appears to be intermittent. 

**maas-ui version**
tip

**MAAS version**
2.9

**LP issue**
Is this an [issue on launchpad](https://bugs.launchpad.net/maas)? If so, please provide a bug is in the form lp#number.

**To Reproduce**
1. Configure external auth
2. login to maas using an rbac user
3. logout
4. See error (may take several attempts)

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by huwshimi** [comment]
I think we can close this until we're able to reproduce it (we haven't seen it since).
