### ISSUE TITLE
Tabstrip underline is glitchy

### ISSUE THREAD

**Issue by lyubomir-popov** [canonical-web-and-design/maas-ui#1841]
**Describe the bug**
There's a staircased bar (right bottom edge) and unnecessary border under the tabstrip. Since we use a drop shadow the border can be removed (and was a while ago):

![image](https://user-images.githubusercontent.com/2741678/98132215-08789980-1eb4-11eb-861c-a3f8dfd4bd6d.png)

**Comment by Caleb-Ellis** [comment]
This is being fixed with the React migration
