### ISSUE TITLE
Fix add machine Cypress test

### ISSUE THREAD

**Issue by huwshimi** [canonical-web-and-design/maas-ui#1852]
The Cypress test to add a machine is failing on master.
**UPDATE:** Blocked because it's pending decision on what tool we should be using moving forward. This should be picked up as a bigger initiative in 21.10.

**Comment by cristinadresch** [comment]
@anthonydillon @Caleb-Ellis @huwshimi @hatched should we block this for now? or should we fix this short term and look for other tools in the long term? We have been carrying forward this issue for ages now

**Comment by anthonydillon** [comment]
Unfortunately, I believe its lower priority than the roadmap items. Let's triage this one and we could schedule an integration sprint early next cycle?

Sound ok @Caleb-Ellis @huwshimi @hatched

**Comment by hatched** [comment]
Looking at the roadmap yeah I think this one needs a concerted effort and research put into it. Especially because this is something we should be implementing on other projects too.

Next cycle it is!

**Comment by Caleb-Ellis** [comment]
This doesn't appear flaky anymore (though there is still some element of flakiness in our other Cypress tests). Closing this issue with the understanding we already have two epics for improving cypress tests
