### ISSUE TITLE
Add close link at bottom of script src code blocks

### ISSUE THREAD

**Issue by squidsoup** [canonical-web-and-design/maas-ui#189]
https://github.com/canonical-web-and-design/maas-ui/pull/183#issuecomment-529525065

**Comment by huwshimi** [comment]
@lilyvidenova do you have any thoughts about this one?

**Comment by cristinadresch** [comment]
@lyubomir-popov you're ok to look into this one this week?

**Comment by lyubomir-popov** [comment]
Yes, let's add it to next iteration.

**Comment by lyubomir-popov** [comment]
Proposal:

![close code snippet](https://user-images.githubusercontent.com/2741678/75354745-683e8f80-58a5-11ea-80b1-c78b6b38cabd.png)
