### ISSUE TITLE
Consolidate toggle button in ScriptsList and DHCPList

### ISSUE THREAD

**Issue by squidsoup** [canonical-web-and-design/maas-ui#190]
DhcpList and ScriptsList both have toggle-able buttons, these styles could be consolidated into a new component.

button could be a component with those styles: https://github.com/canonical-web-and-design/maas-ui/blob/master/ui/src/app/settings/views/Dhcp/DhcpList/DhcpList.js#L86

![image.png](https://images.zenhubusercontent.com/5b15b1fca281cf5395ef819b/79819892-5ef2-478e-ac14-d4249809a75c)

Currently both the DhcpList and ScriptsList have duplicated SCSS for the in-table toggle button:

![image](https://user-images.githubusercontent.com/130286/64574245-b973c900-d3c2-11e9-93c5-e7d4cf6977b0.png)

These should be consolidated into a component.

Additionally, @lyubomir-popov has suggested a change to how the focus outline behaves https://github.com/canonical-web-and-design/maas-ui/pull/183#issuecomment-529523894 which can be addressed here.

@huwshimi has provided an example of how can achieve that in [a codepen](https://codepen.io/huwshimi/pen/rNBdLbP), resulting in something like:

![image](https://user-images.githubusercontent.com/130286/64574310-05267280-d3c3-11e9-89af-c300113009a0.png)

@lyubomir-popov this seems like a good opportunity to perhaps have a think about how the toggle states should appear. We could use a custom style here instead of the browser default (in Chome, the blue outline, in Firefox, a dotted outline). Do you have a bit of bandwidth to design something, or shall we stick to the browser defaults?

**Comment by lyubomir-popov** [comment]
@squidsoup @huwshimi we already have a focus state in vanilla, you can invoke it with: ```@include vf-focus;```.

Looks like this:

![image](https://user-images.githubusercontent.com/2741678/64602016-e372be80-d3b5-11e9-8092-dc5ca118bbc4.png)

**Comment by lyubomir-popov** [comment]
might be worth exposing it as a class so it can be applied on demand what do you think @deadlight?
