### ISSUE TITLE
Opening 'Add partition' form opens all forms

### ISSUE THREAD

**Issue by huwshimi** [canonical-web-and-design/maas-ui#1929]
On the machine storage tab the "Add partition" expanding row opens for all rows.

<img width="1206" alt="Screen Shot 2020-11-26 at 11 47 59 am" src="https://user-images.githubusercontent.com/361637/100296720-10be8300-2fe1-11eb-8d16-1f36dacb0b49.png">

**Comment by Caleb-Ellis** [comment]
@huwshimi interesting. I think it's possible it doesn't open all rows, but inste the disk id and partition id happen to be identical here. I think prefixing the expanded id with either `disk` or `partition` should fix it.

**Comment by Caleb-Ellis** [comment]
This should have been fixed in #1960 - I'm almost certain the issue was disks and partitions having the same `id`, so now each storage device is prefixed by its type followed by its id e.g "disk-123" and "partition-456"
