### ISSUE TITLE
Get CSRF token from API

### ISSUE THREAD

**Issue by squidsoup** [canonical-web-and-design/maas-ui#194]
The MAAS engineering team have made CSRF tokens available from the API.

https://code.launchpad.net/~blake-rouse/maas/+git/maas/+merge/372113

**Comment by cristinadresch** [comment]
@huwshimi is this still blocked?

**Comment by sparkiegeek** [comment]
Note with the fix for https://pad.lv/1844796 landed I expect this to succeed now, do re-open on LP if you see issues?

**Comment by huwshimi** [comment]
There are some additional issues here, I've replied, but we'll probably need to make a slightly different plan.

**Comment by cristinadresch** [comment]
@squidsoup @huwshimi should we close this for now until we figure out the plan? or leave it blocked and move it to next iteration?

**Comment by huwshimi** [comment]
@cristinadresch We may not need this one, I'll move it to backlog.

**Comment by huwshimi** [comment]
We do not have a need for this one anymore it seems.
