### ISSUE TITLE
Improve settings sidenav at small resolutions

### ISSUE THREAD

**Issue by squidsoup** [canonical-web-and-design/maas-ui#195]
From @lyubomir-popov 
```
@media (max-width: $breakpoint-medium) {
  .settings-nav__list {
      columns: 2;
  }
  .settings-nav__list .settings-nav__list .settings-nav__item + .settings-nav__item {
    border-top: 1px solid $color-mid-light;
  }
}
```

**Comment by lyubomir-popov** [comment]
Updated the snippet above to not include code that is already there.

**Comment by lyubomir-popov** [comment]
@huwshimi I must have omitted a line or two. I'll make a branch instead of pasting snippets.

**Comment by huwshimi** [comment]
Thanks a lot @lyubomir-popov!

**Comment by cristinadresch** [comment]
@lyubomir-popov did you do this one? should we close it?

**Comment by cristinadresch** [comment]
We will tackle this as part of the sidenav pattern in 20.04

**Comment by lyubomir-popov** [comment]
Removing estimate as this needs some more work.

**Comment by huwshimi** [comment]
I think we can close this from MAAS as the side nav is being worked on in Vanilla.
