### ISSUE TITLE
Active machine tab isn't highlighted

### ISSUE THREAD

**Issue by huwshimi** [canonical-web-and-design/maas-ui#2024]
When viewing the React machine details the active tab (summary, network etc) isn't highlighted (no underline).

**Comment by Caleb-Ellis** [comment]
Weird. The `aria-selected` attribute updates correctly, but the pseudo-element doesn't appear until you click or interact with the page in some way

**Comment by Caleb-Ellis** [comment]
> I found a strange behaviour when I was browsing around the settings side Nav
> 
> To replicate:
> [1]. click on General (under configuration)
> 
>     * the tab is highlighted with a gray background
> 
> 
> [2]. click configuration
> 
>     * the "General" tab is highlight with a black border on the left
> 
> 
> The same behaviour goes for all other Navs. The strangest one is when I click "Users" the tab is highlighted in gray. Then I click "Images" the "Users" tab is still highlighted in gray but with black border on the left.
> 
> reference to [1]
> ![Screen Shot 2021-01-04 at 3.40.19 PM.png](https://camo.githubusercontent.com/60c7c3a3dcef5fde34edc32581ad6b5872647ff5b69eda6ba1dc4edc82c2a7c3/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3565363632386530666639613363636238343637376232662f30333434623366382d633464322d346234372d393433382d393837313263306363646231)
> 
> reference to [2]
> ![Screen Shot 2021-01-04 at 3.40.30 PM.png](https://camo.githubusercontent.com/73807fbe330a803629f71460b1ff1705012808b7e78774bbc9d98133b7652007/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3565363632386530666639613363636238343637376232662f63663437383165342d346132372d343031382d383965632d343436653664636133666134)

**Comment by anthonydillon** [comment]
When this one is closed can you ensure we circle back and fix commit this LP bug: https://bugs.launchpad.net/bugs/1918966
