### ISSUE TITLE
Add select filter

### ISSUE THREAD

**Issue by huwshimi** [canonical-web-and-design/maas-ui#203]
In the dhcp forms when selecting a node (e.g. machine) where the select could contain a lot of options it'd be nice to add a way to type in the select and have the options filtered. See: https://github.com/canonical-web-and-design/maas-ui/pull/197#issuecomment-530772624

**Comment by Caleb-Ellis** [comment]
@huwshimi @lilyvidenova We have this component in RBAC (LogsFilter) that we could try turning into a common component:

### Nothing selected
![screenshot_8](https://user-images.githubusercontent.com/25733845/64845503-a05d5900-d60a-11e9-9378-bc94dcbcc5ac.png)

### Option selected
![screenshot_11](https://user-images.githubusercontent.com/25733845/64845587-e1556d80-d60a-11e9-899f-d61b056fd3fa.png)

**Comment by huwshimi** [comment]
Will hopefully be added by: https://github.com/canonical-web-and-design/vanilla-framework/issues/2673

**Comment by Caleb-Ellis** [comment]
Blocked until Vanilla implementation complete

**Comment by huwshimi** [comment]
This can now be implemented in the same way as this: https://github.com/canonical-web-and-design/maas-ui/pull/3084.

**Comment by Caleb-Ellis** [comment]
Latest state of this is captured here: https://github.com/canonical-web-and-design/app-tribe/issues/848
