### ISSUE TITLE
Add `is-dense` to TableMenu to stop it jumping so much while loading

### ISSUE THREAD

**Issue by anthonydillon** [canonical-web-and-design/maas-ui#2172]
**Describe the bug**
When actions load over a table it increases the size of the table row. Therefore the rows move as the data loads in. The TableMenu should be the same height as the min-height of a row so this does not happen.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to a machine
2. Click on commissioning (ensure its the React version)
4. See that if you have a long list of commissioning tests the actions appear after the data and change the height of the row.

**Expected behaviour**
The action should appear without effecting the row height. Adding `is-dense` to the button makes this better but doesn't solve it.

**Comment by huwshimi** [comment]
@anthonydillon I've only seen this when running `dotrun ui` but looks fine with `dotrun` is that the case for you?

**Comment by anthonydillon** [comment]
I think your right, sorry. It seems to be just `ui`.

**Comment by huwshimi** [comment]
Yeah it catches us all out. It would be nice if the css is the same. I've filed https://github.com/canonical-web-and-design/maas-ui/issues/2176 to investigate.
