### ISSUE TITLE
Loading a none existing machine details does not error

### ISSUE THREAD

**Issue by anthonydillon** [canonical-web-and-design/maas-ui#2195]
**Describe the bug**
When clicking links or bookmarks to deleted machines the UI never loads.

**maas-ui version**
Latest on bolla

**MAAS version**
MAAS: 2.10.0~alpha1 (9487-g.94cb126c8)

**To Reproduce**
1. Go to http://bolla.internal:5240/MAAS/r/machine/yndnkm/testing
2. Check it doesn't load anything to display any error

**Expected behavior**
The UI should respond with a 404 error and show a message that the machine does not exist.

**Comment by huwshimi** [comment]
I think this should also fix this issue: https://github.com/canonical-web-and-design/maas-ui/issues/1914

**Comment by anthonydillon** [comment]
Wouldn't this confused a user? It would be clearer if they landed on a view that was clear the URL no longer exists? Maybe a follow up?

**Comment by huwshimi** [comment]
> Wouldn't this confused a user? It would be clearer if they landed on a view that was clear the URL no longer exists? Maybe a follow up?

Yep, you're right, this should show a "machine does not exist" warning whereas the delete should redirect to the machine list.
