### ISSUE TITLE
clicking on 'arch' checkbox selects wrong arch

### ISSUE THREAD

**Issue by ddstreet** [canonical-web-and-design/maas-ui#2263]
**Describe the bug**
On the 'images' tab, when clicking on one of the 'arch' checkboxes, the wrong arch is toggled

**maas-ui version**
2.9.2 (9164-g.ac176b5c4)

**MAAS version**
2.9.2 (9164-g.ac176b5c4)

**LP issue**
no, since this is (presumably) ui-only issue

**To Reproduce**
1. Go to web ui, select 'images' tab
2. Click on checkbox beside 'arm64'
3. Note that 'arm64' checkbox was not toggled, instead 'armhf' checkbox was toggled

The arch names can also be clicked, and that does result in toggling the correct checkbox; only clicking directly on the checkbox toggles the wrong checkbox

**Expected behavior**
toggle the clicked checkbox

**Screenshots**
not needed

**Desktop (please complete the following information):**
ubuntu chrome

**Comment by huwshimi** [comment]
I wasn't able to reproduce in Chrome, but in Firefox clicking the bottom half of a checkbox is checking the box below it.

**Comment by ddstreet** [comment]
https://user-images.githubusercontent.com/660812/109070529-9e813b80-76c0-11eb-8d22-f5eaa9a3b0bd.mp4

**Comment by anthonydillon** [comment]
@huwshimi Vanilla updated [the checkbox mark up](https://vanillaframework.io/docs/base/forms#checkbox) by wrapping checkboxes in a `p-checkbox` class to stop them leaking out. This could be the fix.

**Comment by Caleb-Ellis** [comment]
This has been fixed as part of the React migration and will be released in v3.1
