### ISSUE TITLE
Storage input validation unhelpful for rounded values

### ISSUE THREAD

**Issue by huwshimi** [canonical-web-and-design/maas-ui#2396]
In the new storage forms when entering sizes there are sometimes rounding issues that result in errors like the following:

<img width="547" alt="Screen Shot 2021-03-16 at 2 29 03 pm" src="https://user-images.githubusercontent.com/361637/111251878-2de89180-8664-11eb-9ecc-ff4a808a74d0.png">

**Comment by Caleb-Ellis** [comment]
This should probably wait on https://github.com/canonical-web-and-design/maas-squad/issues/2274 so we calculate with the "proper" available size.

**Comment by Caleb-Ellis** [comment]
Removing from storage epic so I can close it - we can fix this as a maintenance task in the future
