### ISSUE TITLE
Add scroll fade to LXD project storage section

### ISSUE THREAD

**Issue by Caleb-Ellis** [canonical-web-and-design/maas-ui#2432]
In the LXD project card, if it has 3 or 4 storage pools a fade gradient is shown to indicate there are more storage pools to scroll down to. We should create a hook that tracks scroll position and does something for certain triggers, e.g. if the component is at the bottom of the scroll position, remove the fade gradient.

**Comment by huwshimi** [comment]
Not sure if this hook could help you, or at least give you a starting point: https://github.com/canonical-web-and-design/react-components/blob/master/src/hooks/useWindowFitment.ts

**Comment by Caleb-Ellis** [comment]
Closing as it was decided to avoid having internal scrollbars, and just collapse to the cards at >2 pools instead of >4 pools
