### ISSUE TITLE
Release notes

### ISSUE THREAD

**Issue by huwshimi** [canonical-web-and-design/maas-ui#2574]
Review the release notes and add anything we have missed:

https://discourse.maas.io/t/3-0-release-notes-collection-point/4279/4

**Comment by Caleb-Ellis** [comment]
I've updated my comment to include the KVM list and KVM details updates. I'll add the GRUB improvements once they're ready.

**Comment by huwshimi** [comment]
I've added notes about the logs/events tab merge. That's the main topics covered.
