### ISSUE TITLE
Client stuck on loading if issue parsing csrf token on server

### ISSUE THREAD

**Issue by squidsoup** [canonical-web-and-design/maas-ui#27]
If maas server has csrf authentication enabled, the client will sit in a "loading" state indefinitely without an error.

The client should be raising a PROTOCOL_ERROR with the error "Invalid CSRF token", but this is not surfaced to the client.

**Comment by huwshimi** [comment]
Closed by: https://github.com/canonical-web-and-design/maas-ui/pull/269
