### ISSUE TITLE
Update argPath arguments to use object keys

### ISSUE THREAD

**Issue by Caleb-Ellis** [canonical-web-and-design/maas-ui#2756]
`domainsURLs.details(null, true)` doesn't tell me what's happening here. I have to find the code where `details` is defined and inspect the function (and the resulting rabbit hole of the undocumented arguments of `argPath` ;) ). Instead of using positional arguments for boolean values it might be better for clarity to use an object with keys.

```js
domainsURLs.details({
  args: null,
  unmodified: true
})
```

_Originally posted by @hatched in https://github.com/canonical-web-and-design/maas-ui/pull/2754#discussion_r648540134_

**Comment by huwshimi** [comment]
This could also add a docstring for the function it generates, this way your IDE will show descriptions for the function args.

**Comment by hatched** [comment]
Right but a lot of time code isn't read in an IDE....like in a PR for example :D

But yeah even having proper docstrings would have helped here.
