### ISSUE TITLE
[Images] improve new images page UX

### ISSUE THREAD

**Issue by Caleb-Ellis** [canonical-web-and-design/maas-ui#2868]
- [ ] Allow removing selected images from the table
- [ ] Don't remove architecture column on small viewports

**Comment by albertodonato** [comment]
I got into a weird situation testing removing/adding other images. I clicked the trash icon to remove "Centos 8", confirmed, after the button showed the spinning icon, table row went back to green, but  reloading the page, the image was gone.

Then I tried to add it back, selected and clicked "update selection", icon keeps spinning and if I reload the page the image wasn't selected.

**Comment by Caleb-Ellis** [comment]
@albertodonato those issues might be due to #2873 - we're currently only polling once every 10 seconds so there can be a bit of a delay between the action and the response. Anyway I've got a fix waiting to land that should make the delay more like ~1 second (depending on the connection to the server). Beyond that though the `bootresource` websocket actions seem to take much longer to resolve than any others - the spinner icon is indicative that the UI is waiting on a response from the server.
