### ISSUE TITLE
Frontend validation for commissioning and testing scripts

### ISSUE THREAD

**Issue by igorgnip-gmail** [canonical-web-and-design/maas-ui#2906]
**Describe the bug**
On latest firefox beta at least - files with .sh or .py extension are denied uploading. When renamed to .txt they are permitted.
Please just consider removing this frontend file/content type validation completely as it serves no purpose.
One could even upload binaries that start with bash shebang and then strip binary part to a different file and execute it. 

**maas-ui version**
at least since maas 2.7.3

**MAAS version**
Version of MAAS affected.
 2.7.3 (8291-g.384e521e6-0ubuntu1~18.04.2) -> unknown
**LP issue**
none submited
**To Reproduce**
1. Go to 'settings'
2. Click on left hand side commissioning scripts under scripts section
3. Click on large upload container and browse to a file with .sh or .py extension.
4. Click upload, see error
5. Rename file to .txt
6. See that you can upload files that way. If you close this loophole, there will be no way at all to upload scripts from ui.

**Expected behavior**
Expected is to check for file extensions and allow .py .sh and possibly other shortlisted extensions to be uploaded.
.txt is not on that list but it is *** fantastic *** that it works. Do not close this!

**Screenshots**
no need

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Firefox 92 beta 6
 - Version 92 beta 6

**Additional context**
Please Backport to 2.7.3 and all other more recent releases. This validation is causing issues.

**Comment by huwshimi** [comment]
Hi @igorgnip-gmail, thanks for this report. We have made this fix for 2.7 and later. It has been released in 2.8 and later and will be released in the next 2.7 bugfix release.

Original issue: https://github.com/canonical-web-and-design/maas-ui/issues/1666.
