### ISSUE TITLE
How to run maas-ui

### ISSUE THREAD

**Issue by ipchaube** [canonical-web-and-design/maas-ui#2908]
Hi Their,
I am tryin to compile and run maas ui on my ubuntu PC. I am able to compile and when do npm start. UI is not loading login screen.
Please help me to make it up.

Thanks,
Indu

**Comment by hatched** [comment]
Can you please elaborate on the steps you've taken so far and if there were any errors in the browser console or CLI output. It will also help us to know what version of Ubuntu/Node/yarn you're running.

**Comment by ipchaube** [comment]
I did git clone maas-ui  and npm install and then npm start
http://localhost:8400/MAAS/r
Error occured while trying to proxy: localhost:8400/MAAS/r

Please she if you can share the right steps and dependency to make UI up and running will help.

**Comment by huwshimi** [comment]
Hi @ipchaube, maas-ui requires a running MAAS to communicate with. Have you set a `MAAS_URL`? Further details here: https://github.com/canonical-web-and-design/maas-ui/blob/master/HACKING.md#edit-local-config

**Comment by ipchaube** [comment]
Thank you for help now I have my instance up and running.
