### ISSUE TITLE
Password visible when inspecting element

### ISSUE THREAD

**Issue by joalif** [canonical-web-and-design/maas-ui#2909]
**Describe the bug**
Passwords are  visible when inspecting elements.

**maas-ui version**
I've tested with latest maas-ui and can reproduce it.

**MAAS version**
Version of MAAS affected : 3.0, 2.9

**LP issue**
Related LP bug : https://bugs.launchpad.net/maas/+bug/1917090
Although it is marked as fixed released in maas-ui, I tested with the latest maas-ui ( commit 7a6965c6189052e0df4588df580b19ad5117fc34) and can still see the passwords.

**To Reproduce**
First reproducer : 
1. Go to KVM tab
2. Create a kvm host
3. Once created, go to KVM Configuration
4. Inspect Password field and you'll able to see the password

Second reproducer :
1. Go to admin tab
2. Click on 'Change password'
3. Inspect the 'Current password' field, you can see the password

**Expected behavior**
Password value not being visible.

**Additional context**
For the KVM case, in ui/src/app/kvm/views/KVMDetails/KVMConfiguration/KVMConfigurationFields/KVMConfigurationFields.tsx , the password field has type="password" but this doesn't seem to have any effect.

**Comment by huwshimi** [comment]
Hi @joalif, thanks for this issue.

In response to your first case I've [filed a bug](https://bugs.launchpad.net/maas/+bug/1938754) about not returning the power parameters from the API.

For the second case I've [filed another issue](https://github.com/canonical-web-and-design/maas-ui/issues/2921) as those inputs should be cleaned up once the password has been changed.

**Comment by Caleb-Ellis** [comment]
This will be fixed as part of the Vault integration work
