### ISSUE TITLE
npm start unable to start maas-ui on window

### ISSUE THREAD

**Issue by ipchaube** [canonical-web-and-design/maas-ui#2922]
$ npm start

> maas-ui-monorepo@1.3.1-monorepo start D:\Projects\MAAS\maas-ui
> yarn serve

yarn run v1.22.10
$ cd proxy && yarn start
$ node ./scripts/start.js && yarn build-shared && concurrently "yarn serve-apps" "yarn serve-base-wait" "yarn show-ready"

*****************

Wait for all clients to load.

*****************

$ cd ../shared && yarn build
$ yarn build-declaration && babel src --out-dir dist --extensions '.js,.jsx,.ts,.tsx'
$ tsc
You have mistakenly installed the `babel` package, which is a no-op in Babel 6.
Babel's CLI commands have been moved from the `babel` package to the `babel-cli` package.

    npm uninstall babel
    npm install --save-dev babel-cli

See http://babeljs.io/docs/usage/cli/ for setup instructions.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! maas-ui-monorepo@1.3.1-monorepo start: `yarn serve`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the maas-ui-monorepo@1.3.1-monorepo start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\praka\AppData\Roaming\npm-cache\_logs\2021-08-04T00_34_47_587Z-debug.log

praka@DESKTOP-BJOI30H MINGW64 /d/Projects/MAAS/maas-ui (master)
$

**Comment by Caleb-Ellis** [comment]
Hi @ipchaube,

Thanks for filing this bug. I wonder if there is some discrepancy between a local and global installation of `babel`. Can you try editing `shared/package.json`, specifically on line 13 replace it with:
```
"build": "yarn build-declaration && ./node_modules/.bin/babel src --out-dir dist --extensions '.js,.jsx,.ts,.tsx'",
```

This should force using a local installation of `babel`.

**Comment by Caleb-Ellis** [comment]
Closing for now - please reopen if you're still seeing issues with a local installation of babel
