### ISSUE TITLE
cloud-init Read More link in UI results in a 404 error

### ISSUE THREAD

**Issue by cpg1111** [canonical-web-and-design/maas-ui#3014]
It appears the UI is linking to an old URL in the docs, and has since been moved.

Originally reported at:
  https://bugs.launchpad.net/bugs/1942115

MAAS version: 2.9.2 (9165-g.c3e7848d1) Snap

when deploying a note there's the option for adding cloud-init user-data info and a "Read More" link for documentation. That link is this:

https://maas.io/docs/custom-node-setup-preseed#heading--cloud-init

but when I click that it takes me to a 404 error page at maas.io.

Doing a bit of digging and this link does work:

https://maas.io/docs/snap/3.0/ui/how-to-customise-machines#heading--how-to-customise-machines-with-cloud-init

and seems to be the relevant information.

The other "Read More" link for KVM Hosts does work, so it looks like just that one link is bad.

**Comment by huwshimi** [comment]
This will be fixed by a docs redirect so no UI changes need to be made
