### ISSUE TITLE
Explore ways to improve errors in Redux state

### ISSUE THREAD

**Issue by Caleb-Ellis** [canonical-web-and-design/maas-ui#3055]
In some cases we have two separate forms on a page that both dispatch the same action when submitted, e.g. KVM config has two forms that call `podActions.update()`. If an error is returned it will show up in both forms. We should find a way to link an error with the form that submitted it, or alternatively, track in form state whether it has been submitted or not and show an error based on that.

**Comment by Caleb-Ellis** [comment]
@huwshimi I've been thinking about our current error handling in Redux and I wonder if we should just remove the `errors` key in favour of `eventErrors` (and maybe just rename *that* to `errors`). I think at the start of the React conversion having `errors` was convenient because there weren't many models performing many actions but now it feels a bit disconnected having a "random" error string in state.

Anyway, about this issue specifically, if we used `eventErrors` I was thinking we could include a form id with the action dispatch, which would then be carried through `action.meta` to the error if one occurs, e.g.

#### **`Form.tsx`**
``` typescript
const id = useRef(nanoid()); // or could have predefined list of form ids
const error = useSelector((state: RootState) =>
  modelSelectors.getLatestError({
    formAction: FormActions.FOO,
    formId: id.current,
  })
);

return (
  <FormikForm
    error={error}
    onSubmit={(values) => {
      dispatch(modelActions.foo({ formId: id.current, ...values }));
    }}
  />
);
```

#### **`model/slice.ts`**
``` typescript
const reducers = {
  foo: {
    prepare: (params: FooParams, { formId }: FormDetails) => ({
      meta: {
        formAction: FormActions.FOO,
        formId,
        model: ModelMeta.MODEL,
        method: "foo-method",
      },
      payload: {
        params,
      },
    }),
    reducer: () => {
      // No state changes need to be handled for this action.
    },
  },
  fooError: {
    prepare: ({ formAction, formId, modelId, payload }) => ({
      meta: {
        formAction,
        formId,
        modelId,
      },
      payload,
    }),
    reducer: (
      state: ModelState,
      action: PayloadAction<ModelError, string, ModelActionMeta>
    ) => {
      state.errors.push({
        formAction: action.meta.formAction,
        formId: action.meta.formId,
        modelId: action.meta.modelId,
        error: action.payload,
      });
    },
  },
};
```

...or something to that effect anyway. I'll try it out with zones since I think that's the simplest model type.

**Comment by Caleb-Ellis** [comment]
Removing this from the 3.1 epic - this will require a pretty substantial amount of work to do it right, and at the moment it's really just "a bit awkward" than broken. Hopefully we can revisit this early next cycle.

**Comment by anthonydillon** [comment]
@Caleb-Ellis this issue is missing all the project tracking meta data.

**Comment by petermakowski** [comment]
@Caleb-Ellis not sure if that'd be of any use for you, but just in case - I started looking into refactoring all boolean statuses into a single status string on my branch here: https://github.com/petermakowski/maas-ui/tree/refactor-generic-actions-single-status-string 

I got it mostly working (except a lot of tests that are failing), but the biggest lesson I've learnt is that it's most likely a bad idea to do it all in bulk (even if it's just changing a status shape across redux).

Tests are tightly coupled to the previous implementation and it's going to be a lot of work to update them to work with the single status string.
