### ISSUE TITLE
Canonical banner in footer oversized on narrow viewports

### ISSUE THREAD

**Issue by albertodonato** [canonical-web-and-design/maas-ui#3091]
**Describe the bug**

The Canonical banner in the UI footer is very large on a narrow viewport.

**MAAS version**
Current master (3.1 beta builds)

**Screenshots**
![image](https://user-images.githubusercontent.com/3472143/135602931-8087883a-3e70-48cd-81e5-f5f419bd69cf.png)

**Desktop (please complete the following information):**
Tested on Ubuntu 21.04 with Firefox 92

**Comment by anthonydillon** [comment]
This issue is missing sprint and epic
