### ISSUE TITLE
Add window title

### ISSUE THREAD

**Issue by huwshimi** [canonical-web-and-design/maas-ui#31]
Display the current page in the window title + fetch and display the maas name in the format `[page name] | [maas name] MAAAS` e.g. "Settings | mymaas MAAS".

**Comment by steverydz** [comment]
I was going to tackle this issue but haven't bee able to get the app running.

I've copied `.env.development` to `.env.development.local` and put the following inside it:

```
REACT_APP_BASENAME="/MAAS/settings"
REACT_APP_MAAS_URL="http://maas.local:5240/MAAS",
REACT_APP_WEBSOCKET_URL="ws://maas.local:5240/MAAS/ws"
```

I had my local MAAS running. I then ran `./run` from the root of the project. The development server started but in the browser all I got was a message: `Failed to connect. Please try refreshing your browser.`

I couldn't find the info on how to hack a local MAAS, but I understood that wasn't necessary anymore.

Not sure if I'm missing any steps or misunderstanding something here?

**Comment by squidsoup** [comment]
@steverydz are you running maas and maas-ui from the same container? If not, you'll need to manually add a csrf token.

**Comment by steverydz** [comment]
@squidsoup Ah, thanks. That has worked.
