### ISSUE TITLE
Navigating to legacy and then clicking back before it's loaded creates some weird CSS (production)

### ISSUE THREAD

**Issue by huwshimi** [canonical-web-and-design/maas-ui#3103]

**Comment by huwshimi** [comment]
@Caleb-Ellis do you happen to remember where we saw this issue? I remember it came up when QAing a PR, but I neglected to link it.

**Comment by Caleb-Ellis** [comment]
@huwshimi I remember there were a lot of spacing issues and the table headers looked janky, but maybe that's slowly been fixed as we remove more legacy code?

All I can see now is a bit of misalignment in the table headers when navigating to controller details and hitting back.

**Comment by Caleb-Ellis** [comment]
This will be fixed when we migrate controller details to React
