### ISSUE TITLE
Request to add identity to a MAAS installation

### ISSUE THREAD

**Issue by anthonydillon** [canonical-web-and-design/maas-ui#3130]
Request to provide theming to indentify which MAAS UI you are looking at a glance.

Original request: https://discourse.maas.io/t/feature-request-custom-ui-themes-to-identify-maas-environment-being-used/5351

I believe this would eventually become a good feature for meta-maas or MAAS central but we could provide a local setting for now which would add identity of sorts to the chrome of the UI.

**Comment by Caleb-Ellis** [comment]
This is being address in https://github.com/canonical-web-and-design/app-tribe/issues/930
