### ISSUE TITLE
LXD table columns mismatched on smaller screen sizes

### ISSUE THREAD

**Issue by Caleb-Ellis** [canonical-web-and-design/maas-ui#3215]
Seems like the wrong columns are getting hidden on smaller screen sizes.

![Screenshot 2021-11-02 at 11-28-37 KVM bolla MAAS](https://user-images.githubusercontent.com/25733845/139772092-666b32e6-45c0-41e9-b854-f7e9e780fcc4.png)

**Comment by huwshimi** [comment]
@Caleb-Ellis I've assigned this to you as I'm not quite sure which columns to hide.
