### ISSUE TITLE
Active step in LXD Stepper is unclear

### ISSUE THREAD

**Issue by hatched** [canonical-web-and-design/maas-ui#3225]
It's quite challenging to see which step is active in this stepper. I think we need to increase the contrast on the active one. 

`/MAAS/r/kvm/lxd` "Add LXD Host"

![Screen Shot 2021-11-03 at 11 09 47 AM](https://user-images.githubusercontent.com/532033/140140435-b904cccb-5c16-4e47-9cb0-2ae93b175256.png)

**Comment by lyubomir-popov** [comment]
I agree, this was aligned with the active state of other components, but here the change doesn't happen on user action, so it is hard to distinguish. 

I would propose something like this:

![image](https://user-images.githubusercontent.com/2741678/140154715-e57adcd2-04d8-4386-bdae-4f1b35836660.png)
