### ISSUE TITLE
Disabling machine config forms while not in editing state is an odd pattern

### ISSUE THREAD

**Issue by Caleb-Ellis** [canonical-web-and-design/maas-ui#3281]
![Peek 2021-11-15 15-34](https://user-images.githubusercontent.com/25733845/141727899-f358eb4f-7935-4145-8f85-a7d685dc6c6e.gif)

In the machine config forms we disable the form fields until the form is put in an editing state. A better pattern would be to render the machine fields as plain text, and only convert to form fields once in editing state. The exception is the tag field which already does that.

Relevant files: `ui/src/app/machines/views/MachineDetails/MachineConfiguration/MachineConfiguration.tsx`

**Comment by cristinadresch** [comment]
@Caleb-Ellis to add screenshot of an example of this pattern but using a list instead of field

**Comment by anthonydillon** [comment]
Here is how most other places work currently:
![Peek 2022-01-04 21-41](https://user-images.githubusercontent.com/1413534/148127717-de8c89e6-dcbb-4fc0-aebe-2756d13703b2.gif)

**Comment by cristinadresch** [comment]
We'll mirror the availability zone gif as part of the tag management build
