### ISSUE TITLE
Mark Broken Option Missing from Web GUI

### ISSUE THREAD

**Issue by anthonydillon** [canonical-web-and-design/maas-ui#3301]
Originally reported on discourse: https://discourse.maas.io/t/mark-broken-option-missing-from-web-gui/5541

**Comment by shinybrar** [comment]
If there is a MAAS team member available to work on this, I can provide them access to the MAAS deployment so that they can debug it in detail or I can provide any further details or data dumps needed.

**Comment by Caleb-Ellis** [comment]
@shinybrar This looks like a permissions issue. It seems like the "Mark broken" option is only available to the owner of a particular machine - other users, even with admin rights, cannot mark a machine they do not own as broken. Similarly, a machine with no owner cannot be marked broken. Weirdly though, you can mark a machine you do not own as fixed. 🤷🏽‍♂️ 

Are you able to confirm that the option shows up for a machine that is owned by the user who's currently logged in?

**Comment by shinybrar** [comment]
@Caleb-Ellis 
I can confirm your hypothesis. I am the person who deployed these nodes, and was originally the owner. After going through the `Mark Broken` & `Mark Fixed` cycle I no longer seem to be the owner. I can also confirm I only see the `Mark Broken` for the one machine I do own. So you are right. 

<img width="766" alt="image" src="https://user-images.githubusercontent.com/4196481/143116735-71acf7cd-6668-439b-894e-8f2541af1276.png">


Furthermore, checking the machine configuration on the MAAS CLI, currently *no one* is the owner of the machine.

```bash
maas <profile> machine read <system_id>
```
```
{
   ...
   "pod": null,
    "cpu_test_status_name": "Passed",
    "network_test_status": -1,
    "locked": false,
    "current_installation_result_id": null,
    "memory": 47872,
    "system_id": "ncxx8t",
    "network_test_status_name": "Unknown",
    "owner_data": {},
    "status_message": "",
    "hardware_uuid": <Redacted>,
    "owner": null,
    ...
}

**Comment by huwshimi** [comment]
It looks like this is a bug on the server and is captured in https://bugs.launchpad.net/maas/+bug/1871021
