### ISSUE TITLE
Add a multiple choice field type for power parameters

### ISSUE THREAD

**Issue by cpg1111** [canonical-web-and-design/maas-ui#3388]
**Describe the bug**
For the IPMI power driver, we're extending the parameters to allow the user to set workaround flags (`ipmipower -W <flag>`). This field can take multiple flags, and so the power parameter field type `multiple_choice` has been added on the backend, but the UI still needs to add an input for this type in the power parameters.

**maas-ui version**
HEAD (this is for the next release)

**MAAS version**
HEAD (this is for the next release)

**LP issue**
[lp:1953395](https://bugs.launchpad.net/maas/+bug/1953395)

**To Reproduce**
N/A

**Expected behavior**
Render a multiple choice field.

**Comment by Caleb-Ellis** [comment]
The changes we need to address include:
1. Rendering a multiselect if the field's `field_type === "multiple_choice"`
2. Handling a `default` value that could be an array of values
