### ISSUE TITLE
Handle incoming websocket messages

### ISSUE THREAD

**Issue by huwshimi** [canonical-web-and-design/maas-ui#34]
When changes happen in MAAS e.g. from the CLE, then presumably there are websocket messages sent to the client which are not handled by the normal get/request implementation we have now.

This might require having a mapping of request types to action type e.g. `users.list` to `UPDATE_USERS`, but we need to investigate what the messages contain.

**Comment by huwshimi** [comment]
Adding a package repo from the old angular MAAS triggered this WS message on the new UI:
```
{
action: "create"
data: {id: 3, created: "Tue, 23 Jul. 2019 06:41:57", updated: "Tue, 23 Jul. 2019 06:41:57", name: "test",…}
arches: ["i386", "amd64"]
components: []
created: "Tue, 23 Jul. 2019 06:41:57"
default: false
disable_sources: false
disabled_components: []
disabled_pockets: []
distributions: []
enabled: true
id: 3
key: "test"
name: "test"
updated: "Tue, 23 Jul. 2019 06:41:57"
url: "ppa:test/test"
name: "packagerepository"
type: 2
}
```

**Comment by squidsoup** [comment]
Completed with https://github.com/canonical-web-and-design/maas-ui/pull/97
