### ISSUE TITLE
Investigate circular import issue

### ISSUE THREAD

**Issue by huwshimi** [canonical-web-and-design/maas-ui#3403]
Investigate ways to prevent circular imports from our large index files such as the following:

> What's happening is that we have a [large index file](https://github.com/canonical-web-and-design/maas-ui/blob/67e27f9e251186e283a9417d89da7de425e9c445/ui/src/app/store/utils/index.ts) that exports all the base utils and then we also have a [large index file](https://github.com/canonical-web-and-design/maas-ui/blob/67e27f9e251186e283a9417d89da7de425e9c445/ui/src/app/store/machine/utils/index.ts) that exports all the machine utils.
> 
> I introduced the import into the node utils: `import { isMachineDetails } from "app/store/machine/utils";`, but inside the machine utils we have imports like `import { getLinkInterface, hasInterfaceType } from "app/store/utils";` so because those files are both exported from the index files they end up importing from each other (when compiled).
> 
> When I try to run the code I get errors like "TypeError: Cannot read property 'generateBaseSelectors' of undefined" and the whole thing collapses.
> 
> Or at least that's my understanding of what's going on. Open to suggestions if you think there might be another solution other than changing the import.

_Originally posted by @huwshimi in https://github.com/canonical-web-and-design/maas-ui/pull/3399#discussion_r765297045_

**Comment by Caleb-Ellis** [comment]
Closing as this isn't necessarily a bug and it's not really getting in the way of anything
