### ISSUE TITLE

[Sentry] $digest already in progress

### ISSUE THREAD

**Issue by anthonydillon** [canonical-web-and-design/maas-ui#3432]
**Describe the bug**
It looks like a prominent bug has appeared since the 8th of Dec.

**MAAS version**
2.9.2 (9165-g.c3e7848d1)

**Additional context**
https://sentry.is.canonical.com/canonical/maas-ui/issues/16446/?query=is%3Aunresolved

**Comment by Caleb-Ellis** [comment]
This issue has been marked as resolved. It's also in the VLAN details section which we've since migrated to React, so it won't appear in 3.2 onwards.
