### ISSUE TITLE
IPMI Workaround "None" option should not be displayed and instead set when all other options are unset

### ISSUE THREAD

**Issue by cpg1111** [canonical-web-and-design/maas-ui#3523]
**Describe the bug**
In the multiselect for IPMI workaround options, there is a `None` option displayed, the explicit `None` value is used so that the CLI may unset the default value. However, the UI should hide this option and set it as a value when all other options are unset.

**maas-ui version**
HEAD

**MAAS version**
HEAD

**LP issue**
lp1958173

**To Reproduce**
1. Add a machine with IPMI power management
2. Configure IPMI options
3. Notice the `None` workaround option

**Expected behavior**
All options except `None` are displayed and available for selection, if all of the displayed options are unset, the `None` option is selected.

**Screenshots**

![Screenshot from 2022-01-17 14-44-37](https://user-images.githubusercontent.com/4106605/149829252-08b80946-4c11-4ac1-8558-40f74b44c37c.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 21.10
 - Browser Firefox
 - Version HEAD

**Additional context**
N/A

**Comment by Caleb-Ellis** [comment]
@cpg1111 Is this something we can expect to be used in other multiselect power type fields or is this probably an IPMI-only thing? i.e. should we handle this dynamically or should we special-case IPMI here?

**Comment by cpg1111** [comment]
At least for now, this is unique to the IPMI workaround options. We don't use multiselect for other power types currently.
