### ISSUE TITLE
Controller configuration tab no longer appears

### ISSUE THREAD

**Issue by Caleb-Ellis** [canonical-web-and-design/maas-ui#3728]
It seems like the underlying controller model has been updated and no longer includes the "permissions" key (possibly from [this commit](https://git.launchpad.net/maas/commit/?id=22a3211ac812a0f9414bb06eb2bf725a6f276b96)?). We should 1. file an LP bug about what we need that is missing and 2. update the type accordingly

**Comment by Caleb-Ellis** [comment]
[LP bug](https://bugs.launchpad.net/maas/+bug/1967704)

**Comment by petermakowski** [comment]
@Caleb-Ellis  I wrote an e2e test for this which will pass once it's fixed 
https://github.com/canonical-web-and-design/maas-ui/pull/3863
