### ISSUE TITLE
Old chevron graphic used in some dropdowns

### ISSUE THREAD

**Issue by lyubomir-popov** [canonical-web-and-design/maas-ui#390]
Old chevrons:
<img width="1225" alt="Screenshot 2019-11-04 at 17 47 46" src="https://user-images.githubusercontent.com/2741678/68204193-603da580-ffbf-11e9-9fb5-2d02ac88551b.png">

Latest chevrons (screenshot taken from network discovery):
<img width="206" alt="Screenshot 2019-11-05 at 11 30 14" src="https://user-images.githubusercontent.com/2741678/68204367-b7dc1100-ffbf-11e9-89f8-ef3c171946b6.png">

**Comment by lyubomir-popov** [comment]
Also in dhcp snippets:
![image](https://user-images.githubusercontent.com/2741678/68221642-a572cf00-ffe1-11e9-94f2-ef33910041f1.png)

**Comment by huwshimi** [comment]
@lyubomir-popov the chevron next to description in that shot is supplied by Vanilla:

<img width="1225" alt="Screenshot 2019-11-04 at 17 47 46" src="https://user-images.githubusercontent.com/2741678/68204193-603da580-ffbf-11e9-9fb5-2d02ac88551b.png">

I've filed an issue:
https://github.com/canonical-web-and-design/vanilla-framework/issues/2634
