### ISSUE TITLE
Broken links on VLAN page

### ISSUE THREAD

**Issue by lilyvidenova** [canonical-web-and-design/maas-ui#392]
![image.png](https://images.zenhubusercontent.com/5af976724b5806bc2bd30860/20bd54ca-44b6-496b-9b04-6970d20ab07a)

First one should lead to `/MAAS/r/settings/dhcp`

Second one to `https://maas.io/docs/dhcp`

**Comment by steverydz** [comment]
Fixed by https://github.com/canonical-web-and-design/maas-ui/pull/412
