### ISSUE TITLE
Enforce using userEvent library instead of fireEvent for simulating user interactions

### ISSUE THREAD

**Issue by petermakowski** [canonical-web-and-design/maas-ui#3934]
`userEvent` adds related event calls from browsers to make tests more realistic than its counterpart `fireEvent`, which is a low-level api.

This makes for a more user-centric, and closer-to-truth testing of user interactions.

Ideally this should be fixed before we begin React migration so that new tests follow this rule.

- [ ] add eslint rule https://github.com/testing-library/eslint-plugin-testing-library/blob/main/docs/rules/prefer-user-event.md
- [ ] replace existing `fireEvent` with `userEvent`

**Comment by Caleb-Ellis** [comment]
There are some cases where we want to change a slider value but it looks like this is not supported in userEvent yet
https://github.com/testing-library/user-event/issues/871
