### ISSUE TITLE
Cannot Commission machines from status dropdown 

### ISSUE THREAD

**Issue by casual-lemon** [canonical-web-and-design/maas-ui#3935]
**Describe the bug**
Commission machine failed in MaaS 3.1 During Deployment due  to JS error thrown in console

**maas-ui version**
3.1

**MAAS version**
3.1

**LP issue**
N/A

**To Reproduce**
1. Go to Machines
2. Click on drop down with commission 
3. The checkbox is not marked 
4.  See error in browser debugger console 
5. See attached screenshots. 

**Expected behavior**
The commission of the selected machine to start

**Screenshots**
![Screenshot from 2022-05-13 09-45-33](https://user-images.githubusercontent.com/62671519/168604170-1207530a-a448-4d90-a53c-be931fc891cb.png)

![Screenshot from 2022-05-13 09-39-30](https://user-images.githubusercontent.com/62671519/168604210-36a5efc4-3aa2-4ee6-8e53-549d2d9911c3.png)

![Screenshot from 2022-05-13 09-47-15](https://user-images.githubusercontent.com/62671519/168604314-db42040e-0a9c-412c-95d4-d9fc7f379003.png)

**Desktop (please complete the following information):**
 - OS: ubuntu focal
 - Browser FireFox 
 - Version latest

**Additional context**
This also happens when the machine is New or Ready to be commissioned 
Either disabling the drop down when there is no checkbox  marked or removing it from the status column would be ideal. 
MM chat link https://chat.canonical.com/canonical/pl/t14hphgetfgndqy97c3pwbhjio

**Comment by huwshimi** [comment]
@casual-lemon Thanks a lot for reporting this. I've fixed this and it will be available in the next 3.1.x release.

**Comment by casual-lemon** [comment]
@huwshimi thank you!
