### ISSUE TITLE
Opening a script should scroll you to the top of the row

### ISSUE THREAD

**Issue by lyubomir-popov** [canonical-web-and-design/maas-ui#402]
Opening a script under one that is currently open leads to this:
![image](https://user-images.githubusercontent.com/2741678/68210434-6cc8fa80-ffcd-11e9-805a-622ac9c66d33.png)

Ideally, it should position the top of the script row at the top of the window.

**Comment by huwshimi** [comment]
This should check that the top of the script is off the top of the screen before scrolling to prevent unnecessary scrolls.
