### ISSUE TITLE
Machine listing API code and redux state

### ISSUE THREAD

**Issue by cristinadresch** [canonical-web-and-design/maas-ui#411]

**Comment by cristinadresch** [comment]
@huwshimi no rush on doing this one, but in case you guys fix all the issues found in maas-ui you can move to this next iteration

**Comment by cristinadresch** [comment]
@huwshimi can you add other issues to this pls for the work up to Friday?

**Comment by huwshimi** [comment]
@cristinadresch @steverydz I've added a few more tasks that should keep as going for the remainder of the week.

**Comment by steverydz** [comment]
Thanks @huwshimi that's great!
