### ISSUE TITLE
No websocket responses from remote MAAS

### ISSUE THREAD

**Issue by squidsoup** [canonical-web-and-design/maas-ui#416]
This has just started recently, but I've as yet been unable to pinpoint where the issue is. Authenticating, loading the client and establishing a WS connection to the remote maas succeeds (tested on both karura, my home maas), however no websocket responses are received. 

![image](https://user-images.githubusercontent.com/130286/68341464-5ea1e800-014d-11ea-83b2-287f383ce9c2.png)

This does *not* occur (on maas master), when the client and server are served from the same host/container. So, not an issue for production, but blocking the demoservice and pointing the client at karura. 

If someone can confirm that they're experiencing the same thing, that would be valuable.

**Comment by huwshimi** [comment]
Fixed by: https://github.com/canonical-web-and-design/maas-ui/pull/560
