### ISSUE TITLE
Investigate removal of crypto polyfill

### ISSUE THREAD

**Issue by petermakowski** [canonical-web-and-design/maas-ui#4272]
all browsers that we officially support can handle Web Cryptography natively. We should consider dropping the crypto polyfills that are added to the @canonical/macaroon-bakery especially if it's a dependency of a dependency.

https://webteam.canonical.com/practices/browser-support 
https://caniuse.com/?search=crypto

https://github.com/canonical-web-and-design/maas-ui/pull/4260#issuecomment-1189671239

**Comment by huwshimi** [comment]
I think this issue should probably be on the bakeryjs repo as it doesn't just affect maas-ui.

**Comment by petermakowski** [comment]
Moved https://github.com/juju/bakeryjs/issues/47
