### ISSUE TITLE
Text wraps in tables

### ISSUE THREAD

**Issue by huwshimi** [canonical-web-and-design/maas-ui#449]
When viewing tables at small screen sizes the headers and content cells wrap the content when there is no room.
<img width="614" alt="Screen Shot 2019-11-12 at 11 57 37 am" src="https://user-images.githubusercontent.com/361637/68632815-d2743400-0543-11ea-838f-fa9c01ae7aa8.png">

**Comment by huwshimi** [comment]
@lyubomir-popov @lilyvidenova any suggestions for this one?

**Comment by lilyvidenova** [comment]
Can we drop columns as the screen gets smaller? 
We should drop them in the order: 
- MAAS keys
- Machines
- Type
- Last seen
- Role 
- email

**Comment by huwshimi** [comment]
@lilyvidenova we certainly can, the only issue would be that as there are no longer any detail pages for these tables there would be no way to see that information.

**Comment by lilyvidenova** [comment]
@huwshimi That's okay, I'll think of a nice message to add to smaller screens view to inform the user that there is more information available on the desktop version. I know this is not ideal, however MAAS is not an application users would expect to be able to do/see all detail on a mobile screen. In general, though, I think we should come up with a better pattern on how to treat tables when we show them on small screens.

**Comment by huwshimi** [comment]
OK great, thanks @lilyvidenova. Would it be possible to get the order of fields to drop for each table? I've included all the tables I could find below:


<img width="1437" alt="Screen Shot 2019-11-12 at 12 11 15 pm" src="https://user-images.githubusercontent.com/361637/68633576-837bce00-0546-11ea-816d-7ff4f2c7c7fb.png">
<img width="1437" alt="Screen Shot 2019-11-12 at 12 11 25 pm" src="https://user-images.githubusercontent.com/361637/68633578-837bce00-0546-11ea-8661-5dac238b4be4.png">
<img width="1437" alt="Screen Shot 2019-11-12 at 12 11 31 pm" src="https://user-images.githubusercontent.com/361637/68633579-837bce00-0546-11ea-896d-de03a243b53c.png">
<img width="1437" alt="Screen Shot 2019-11-12 at 12 11 41 pm" src="https://user-images.githubusercontent.com/361637/68633580-837bce00-0546-11ea-92d7-52f5bea13105.png">
<img width="1437" alt="Screen Shot 2019-11-12 at 12 12 11 pm" src="https://user-images.githubusercontent.com/361637/68633581-84146480-0546-11ea-8e6a-d312035fca10.png">
<img width="1437" alt="Screen Shot 2019-11-12 at 12 12 17 pm" src="https://user-images.githubusercontent.com/361637/68633582-84146480-0546-11ea-9f59-d36892cd9644.png">
<img width="1437" alt="Screen Shot 2019-11-12 at 12 13 13 pm" src="https://user-images.githubusercontent.com/361637/68633583-84146480-0546-11ea-868b-25be75d88cec.png">
<img width="1437" alt="Screen Shot 2019-11-12 at 12 14 06 pm" src="https://user-images.githubusercontent.com/361637/68633584-84acfb00-0546-11ea-9619-bc6d5d3fb218.png">
<img width="1437" alt="Screen Shot 2019-11-12 at 12 17 54 pm" src="https://user-images.githubusercontent.com/361637/68633586-84acfb00-0546-11ea-8cc3-01fdc3181c33.png">

**Comment by lilyvidenova** [comment]
> OK great, thanks @lilyvidenova. Would it be possible to get the order of fields to drop for each table? I've included all the tables I could find below:
> 
> <img alt="Screen Shot 2019-11-12 at 12 11 15 pm" width="1437" src="https://user-images.githubusercontent.com/361637/68633576-837bce00-0546-11ea-816d-7ff4f2c7c7fb.png">
> 
Drop key
> <img alt="Screen Shot 2019-11-12 at 12 11 25 pm" width="1437" src="https://user-images.githubusercontent.com/361637/68633578-837bce00-0546-11ea-8661-5dac238b4be4.png">
> 
- key
- ID
> <img alt="Screen Shot 2019-11-12 at 12 11 31 pm" width="1437" src="https://user-images.githubusercontent.com/361637/68633579-837bce00-0546-11ea-896d-de03a243b53c.png">
> 
Truncate key
> <img alt="Screen Shot 2019-11-12 at 12 11 41 pm" width="1437" src="https://user-images.githubusercontent.com/361637/68633580-837bce00-0546-11ea-92d7-52f5bea13105.png">
> 
Did this one above
> <img alt="Screen Shot 2019-11-12 at 12 12 11 pm" width="1437" src="https://user-images.githubusercontent.com/361637/68633581-84146480-0546-11ea-8e6a-d312035fca10.png">
> 
- uploaded on
- description
> <img alt="Screen Shot 2019-11-12 at 12 12 17 pm" width="1437" src="https://user-images.githubusercontent.com/361637/68633582-84146480-0546-11ea-9f59-d36892cd9644.png">
> 
- URL
- enabled
> <img alt="Screen Shot 2019-11-12 at 12 13 13 pm" width="1437" src="https://user-images.githubusercontent.com/361637/68633583-84146480-0546-11ea-868b-25be75d88cec.png">
> 
Drop key
> <img alt="Screen Shot 2019-11-12 at 12 14 06 pm" width="1437" src="https://user-images.githubusercontent.com/361637/68633584-84acfb00-0546-11ea-9619-bc6d5d3fb218.png">
> 
- last edited by
- type
- description
- applies to
> <img alt="Screen Shot 2019-11-12 at 12 17 54 pm" width="1437" src="https://user-images.githubusercontent.com/361637/68633586-84acfb00-0546-11ea-8cc3-01fdc3181c33.png">
Drop Disctro series

**Comment by lilyvidenova** [comment]
Thanks @huwshimi!

**Comment by huwshimi** [comment]
Thanks heaps @lilyvidenova!
