### ISSUE TITLE
Add machine: Clicking on tab strip discards entered data without asking for confirmation

### ISSUE THREAD

**Issue by lyubomir-popov** [canonical-web-and-design/maas-ui#455]
Note: This is for the angular client, only filing because we were asked to QA the Machine summary page.

**Comment by steverydz** [comment]
@lyubomir-popov What do you define the tab strip as? I've tried using the add machine panel, changed all the fields and clicked pretty much everywhere and nothing happens?

**Comment by lyubomir-popov** [comment]
The tabs under the bottom of the form.

**Comment by steverydz** [comment]
@lyubomir-popov oh, so you mean clicking on one of the tabs takes to you wherever that tab goes and cancels the form?

**Comment by lyubomir-popov** [comment]
yes!

**Comment by lilyvidenova** [comment]
I think we should keep this in mind when updating the design of the machine details pages, however we are not going to change the current behaviour in the angular client. I'm removing the milestone and epic from it.

**Comment by Caleb-Ellis** [comment]
This is no longer the case in the React pages - the tabstrip is a separate entity to the header forms so they update independently. If you navigate to an entirely different page (e.g. machine list => KVM) you will lose the form data but I think that makes sense.
