### ISSUE TITLE
Machine summary: grid gaps 2.5 rem instead of 2 rem (the vanilla default)

### ISSUE THREAD

**Issue by lyubomir-popov** [canonical-web-and-design/maas-ui#461]
![image](https://user-images.githubusercontent.com/2741678/68673797-76fa7400-054c-11ea-89b9-48121ad6d758.png)

**Comment by steverydz** [comment]
After speaking with @lyubomir-popov this is because the legacy app is using an older version of vanilla. The variables to set the column gap have since been changed. As there is no plan to upgrade vanilla in the legacy app I'll close this issue.
