### ISSUE TITLE
Inline style not adhering to "Single direction margin declaration" convention used in Vanilla

### ISSUE THREAD

**Issue by lyubomir-popov** [canonical-web-and-design/maas-ui#464]
![image](https://user-images.githubusercontent.com/2741678/68675917-d0fd3880-0550-11ea-917e-96922d9a0858.png)

[Single direction margin declaration](https://csswizardry.com/2012/06/single-direction-margin-declarations/) is a css best practice aimed to eliminate margin collapse among other things.

In vanilla, we apply margins at the bottom of elements.

Often the last element in a group requires more space. One way to do that with vanilla (admittedly it requires a lot of classes, but doesn't require custom css): 
```.p-strip.is-shallow.u-no-padding--top```

I can see this in maas-ui, which is an acceptable alternative, but it should ideally pull the value from one of the predefined values in maas, like the padding of the shallow strip,  so that it stays consistent with other elements: 

```
.p-form__control:last-of-type {
    margin-bottom: 0.5rem;
}

```

In the case of the screenshot above, this small margin is subject to margin collapse, and the bigger inline margin "swallows" it.  Why not just increase the .p-form__control:last-of-type margin and get rid of the inline one? Are there cases where that leads to too much space so you resorted to an inline style?

Just trying to understand the use case here, this might be something vanilla should make easy to achieve without any custom code.

**Comment by Caleb-Ellis** [comment]
@lyubomir-popov I created an issue in Vanilla about form submit buttons being too close to form inputs, with a suggested fix: https://github.com/canonical-web-and-design/vanilla-framework/issues/2497

However I think there are instances in the markup where this is not applied, which has been bandaided with an inline style of `margin-top: 1rem`. I'll see if I can find a way to fix these in a smarter way.

If you want to see how the settings forms look without the inline style just remove `style={{ marginTop: "1rem" }}` from `/ui/src/app/base/components/FormikFormButtons/FormikFormButtons.js`. My initial override can be found in `/ui/src/scss/_vanilla-overrides.scss`.
