### ISSUE TITLE
Settings>Network>Proxy: Form markup issues

### ISSUE THREAD

**Issue by lyubomir-popov** [canonical-web-and-design/maas-ui#465]
Two issues:

1. Sibling radio buttons in vanilla sit closer together than they appear in maas:

![image](https://user-images.githubusercontent.com/2741678/68676832-c9d72a00-0552-11ea-941f-50bba34dcf57.png)

This is because each pair input+label is in a separate parent. Is this required for validation?

2. The preceding text is wrapped in a label. A label has smaller padding, because it expects a field to follow it. Wrapping it in a `<p>` would result in some more spacing under it, further aiding correct visual grouping (description + set of radios + button)

Comparison of 1 and 2 before/after suggested changes:

Before:
![image](https://user-images.githubusercontent.com/2741678/68677034-318d7500-0553-11ea-915b-0e67afdd438c.png)

After:
![image](https://user-images.githubusercontent.com/2741678/68677146-74e7e380-0553-11ea-9063-e8bc714d0039.png)

**Comment by Caleb-Ellis** [comment]
> This is because each pair input+label is in a separate parent. Is this required for validation?

This was required for how we were building forms with Formik v1 using FormikField components. Maybe this can be changed now that we've upgraded to v2?
