### ISSUE TITLE
First names are not correctly saved when adding/editing user

### ISSUE THREAD

**Issue by Caleb-Ellis** [canonical-web-and-design/maas-ui#476]
If you create a new user with the name `Firstname Lastname`, the result in state is:
``` js
{
  first_name: '',
  last_name: 'Lastname',
}
```

**Comment by Caleb-Ellis** [comment]
Turns out this is an issue with the backend. `first_name` is passed through the websocket correctly but it doesn't update in the database. In the old angular forms the "Full name" field was simply showing and editing the `last_name` parameter.

**Comment by cristinadresch** [comment]
@Caleb-Ellis did you open a launchpad bug for this one? pls add 'blocking-ui' as a label too

**Comment by Caleb-Ellis** [comment]
LP bug: https://bugs.launchpad.net/maas/+bug/1853579

**Comment by Caleb-Ellis** [comment]
As per the LP bug the fix will be to use `last_name` and ignore `first_name` for now.
