### ISSUE TITLE
Add secondary table headers and values in the machines table

### ISSUE THREAD

**Issue by steverydz** [canonical-web-and-design/maas-ui#498]
Add the secondary (sub) table headers and their corresponding values to the machines table.

Note: This will require an adjustment to the `MainTable` component from https://github.com/canonical-web-and-design/react-components.

![](https://user-images.githubusercontent.com/361637/69291961-d8ab9400-0c58-11ea-8dae-5a3c7dbc40aa.png)

**Comment by huwshimi** [comment]
@steverydz would you mind filing issues for the changes to MainTable?

Also to note for whoever picks this up, we have a header toggle in the user list component which could probably be turned into a reusable component to handle some of this: https://github.com/canonical-web-and-design/maas-ui/blob/master/ui/src/app/settings/views/Users/UsersList/UsersList.js#L160

**Comment by huwshimi** [comment]
@steverydz Oops, I totally missed that you already filed https://github.com/canonical-web-and-design/react-components/issues/40.

**Comment by steverydz** [comment]
@huwshimi This might not be an issue now as @Caleb-Ellis [pointed out that components can be passed into the content param](https://github.com/canonical-web-and-design/react-components/issues/40#issuecomment-557181707).

**Comment by huwshimi** [comment]
This work will be tracked as part of this epic: https://github.com/canonical-web-and-design/MAAS-squad/issues/1747
