### ISSUE TITLE
Add in table actions and icons to the machines table

### ISSUE THREAD

**Issue by steverydz** [canonical-web-and-design/maas-ui#499]
The previous machines table has action dropdowns for certain fields and icons to represent statuses.

![](https://user-images.githubusercontent.com/361637/69291961-d8ab9400-0c58-11ea-8dae-5a3c7dbc40aa.png)

**Comment by huwshimi** [comment]
This work will be tracked as part of this epic: https://github.com/canonical-web-and-design/MAAS-squad/issues/1696.
