### ISSUE TITLE
Implement white background

### ISSUE THREAD

**Issue by lyubomir-popov** [canonical-web-and-design/maas-ui#513]
Change the app background to white and resolve any issues.

(<a href="https://docs.google.com/document/d/1E2udSndt-uT36NRsKFS8owD2CSGGB4I9LQm5XyYF6kw/edit?pli=1#heading=h.rw8e83l7f1do">doc</a> mentioning possible issues and ways to resolve them )

**Comment by cristinadresch** [comment]
Closing as this has not been a priority for this cycle
