### ISSUE TITLE
Implement authenticating via Candid

### ISSUE THREAD

**Issue by huwshimi** [canonical-web-and-design/maas-ui#514]
@huwshimi commented on [Tue Nov 26 2019](https://github.com/canonical-web-and-design/MAAS-squad/issues/1663)

If the login endpoint returns an external authentication URL then provide a button that uses bakeryjs to authenticate with candid instead of via the Django API.

**Comment by cristinadresch** [comment]
@huwshimi is this blocked on engineers? do you think we'll be able to get it done next week?
