### ISSUE TITLE
Make users read only when using external auth

### ISSUE THREAD

**Issue by huwshimi** [canonical-web-and-design/maas-ui#516]
Disable adding/updating/deleting users and the general user preferences when using external auth.

**Comment by cristinadresch** [comment]
@huwshimi is this blocked on engineers? do you think we'll be able to get it done next week?

**Comment by cristinadresch** [comment]
@huwshimi still ok to finish this one by Friday?

**Comment by huwshimi** [comment]
@cristinadresch yep, should be!
