### ISSUE TITLE
Messages sometimes do not disappear

### ISSUE THREAD

**Issue by huwshimi** [canonical-web-and-design/maas-ui#517]
The notifications after editing etc. sometimes do not time out.

<img width="787" alt="Screen Shot 2019-11-26 at 7 15 09 pm" src="https://user-images.githubusercontent.com/361637/69664974-51f41e00-1081-11ea-8d24-9ab8bb67dd35.png">

**Comment by Caleb-Ellis** [comment]
Fix here: https://github.com/canonical-web-and-design/react-components/pull/45
