### ISSUE TITLE
Only display latest message

### ISSUE THREAD

**Issue by huwshimi** [canonical-web-and-design/maas-ui#525]
When notifications appear they should hide the previous notification if it is still visible.

**Comment by cristinadresch** [comment]
@huwshimi you're going to work on this? I'm moving it to next iteration, so you can focus on the external auth bits

**Comment by Caleb-Ellis** [comment]
@lilyvidenova This one needs a little bit of UX input I think. At the moment we just have a single container (`NotificationList`) that houses all the notifications and puts it at the top of the section. It persists even when navigating between sections/routes, so updating your details in user prefs will show a notification that persists even after navigating to /settings.

Anyway, some things to consider first:
- Do we want to separate out "global" notifications (persistent) with "specific" notifications (temporary)?
- If so, do we want to have a visual difference between the two, e.g. global notifications float on top of the page content (like in RBAC in the bottom left of the screen), and specific notifications just show at the top of the current route?
- Are there going to be instances where we want there to be multiple notifications shown at once? My initial thoughts are that global could probably allow for multiple, and specific could just be the latest.

**Comment by lilyvidenova** [comment]
@Caleb-Ellis 

> Do we want to separate out "global" notifications (persistent) with "specific" notifications (temporary)?
Yes, I think that'll be great and it's an important distinction. I would also like to add that temporary ones should disappear after a consistent, set period of time - not sure if we have that defined already somewhere or not. 

>If so, do we want to have a visual difference between the two, e.g. global notifications float on top of the page content (like in RBAC in the bottom left of the screen), and specific notifications just show at the top of the current route?
Yes, again - excellent idea. 

>Are there going to be instances where we want there to be multiple notifications shown at once? My initial thoughts are that global could probably allow for multiple, and specific could just be the latest.
For 'general' ones - absolutely, I think we should allow any number of notifications to be visible at the same time.
For 'specific' ones - I'd like to say yes, but they should all be temporary, so unless you make a lot of changes in a very short period of time there shouldn't be an issue with too many notifications showing together.

**Comment by squidsoup** [comment]
@cristinadresch @lilyvidenova given this requires a bit of thought, should we drop this from the 2.7 release?

**Comment by lilyvidenova** [comment]
@squidsoup yeah, I agree. And the issue of notifications not disappearing was fixed, so putting this in the icebox.

**Comment by Caleb-Ellis** [comment]
Notifications are getting redesigned. Closing for now. @amylily1011 some details for you to consider
