### ISSUE TITLE
Refactor redux actions

### ISSUE THREAD

**Issue by squidsoup** [canonical-web-and-design/maas-ui#54]
Currently we pass nested redux payloads to our websockets layer, e.g.: 

```javascript
repositories.fetch = () => {
  return {
    type: "WEBSOCKET_SEND",
    payload: {
      actionType: "FETCH_REPOSITORIES",
      message: {
        method: "packagerepository.list",
        params: { limit: 50 },
        type: 0
      }
    }
  };
};
```
This does have the advantage of making the saga code very succinct, but it is a bit unusual and in contravention of [flux standard actions](https://github.com/redux-utilities/flux-standard-action). Instead, we should probably dispatch a payload that looks more like:

```javascript
repositories.fetch = () => (
{
  type: "FETCH_REPOSITORIES",
  meta: {
    limit: 50
  }
})     
``` 

That way the redux actions have no knowledge of the websocket implementation, which can be encapsulated in a saga (`type`, `params`, `method` etc).

**Comment by huwshimi** [comment]
@squidsoup was this closed by: https://github.com/canonical-web-and-design/maas-ui/pull/85 ?
