### ISSUE TITLE
Extra fabrics showing up in Subnets tab 

### ISSUE THREAD

**Issue by lilyvidenova** [canonical-web-and-design/maas-ui#561]
**Describe the bug**
On MAAS 2.7.0 (8169-g.30f255607-0ubuntu1) when going to the Subnets tab I see a lot of extra created fabrics that have grown over time. See attached screenshot.

**MAAS version**
2.7.0 (8169-g.30f255607-0ubuntu1)

**LP issue**
[LP#1853359](https://bugs.launchpad.net/maas/+bug/1853359)? 

**To Reproduce**
I can't really figure out how...maybe we can ask Newell? 

**Screenshots**
![image.png](https://images.zenhubusercontent.com/5af976724b5806bc2bd30860/1e77dbc4-c816-472f-98f5-1b5d9604ab9c)

**Comment by Caleb-Ellis** [comment]
Marked as invalid in lp
