### ISSUE TITLE
Add warnings to package repos 

### ISSUE THREAD

**Issue by lilyvidenova** [canonical-web-and-design/maas-ui#563]
- MAAS should show a warning if the universe component is disabled. As seen here if using a mirror this breaks commissioning. 
- The UI should also show a warning if updates or security pocket is disabled. 
- It would also be nice to show a warning if there isn't a repository for every architecture. That may be a bit more difficult as we split architectures between amd64/i386 and everything else.

Raised by [LP#1851276](https://bugs.launchpad.net/maas/+bug/1851276)

**Comment by lilyvidenova** [comment]
Addressing the first two points: https://app.zeplin.io/project/5ce5423a25863c1e0d7abb27/dashboard?seid=5defae08fa45ecad8e96f344 

@squidsoup @huwshimi could you take a look and decide if adding these warnings is a reasonable ask for the release or if we should put them in the backlog?

**Comment by squidsoup** [comment]
@lilyvidenova a few questions, currently we only provide the option to disable pockets and components for the default archive. If using the options always breaks commissioning, why do we provide these options in the first place?

**Comment by sparkiegeek** [comment]
Note that PPAs don't have pockets and components in the same way.

Custom repos may or may not.

**Comment by sparkiegeek** [comment]
Bumped the LP bug out of the 2.7.0 release

**Comment by amylily1011** [comment]
Follow up on the message on Zeplin - @lilyvidenova 
Lee suggests that we should show the warning in the lay over form when "universe" is selected as well (like a validation message) coupled with the warning message once the saved button is clicked. 

In my opinion, it is always nice to provide a "perceived" control to our users, knowing that it might not be the best practice. Given that we provide a way for them to recover from their mistakes.

**Comment by lilyvidenova** [comment]
@amylily1011 what is the status of this one? what should we do? Is there something we could research independently from the engineers?

**Comment by amylily1011** [comment]
@lilyvidenova the current status is @sparkiegeek needs to find out why we allow the user to disable universe in the first place. I planned to follow up on this on Monday.

**Comment by lilyvidenova** [comment]
@amylily1011 some quick reading about the repos that might be interesting and help suggesting a good solution:

https://askubuntu.com/questions/1178816/how-secure-is-the-universe-repository
https://askubuntu.com/questions/331473/security-updates-for-the-universe-repository-for-lts-releases
https://askubuntu.com/questions/52858/which-ubuntu-repositories-are-totally-safe-and-free-from-malware

**Comment by amylily1011** [comment]
Cool, Thanks Lily!

**Comment by amylily1011** [comment]
According to Lee: 
In a highly restrictive/secure environment a user may decide to create their own repository instead of using one provided by Canonical. Instead of using multiple pockets the user may create one pocket containing the set of packages which are allowed to be used in their environment. In this edge case a user could disable all pockets except main and still have things working.

Assuming these are our extreme users, I think it is still a good thing to allow people to customize their own repo. The solution we have right now is a good addition to help people from making mistakes. In the future, it might be good to consider basic settings VS advance that allows our normal users to go through this seamlessly and our advance users to have the control of what they are doing.

**Comment by lilyvidenova** [comment]
@amylily1011 are you proposing we keep the current design, or to build the proposed design?

**Comment by amylily1011** [comment]
Conclusion for this issue after syncing with @sparkiegeek , let's not add more complexity to the package repo. We don't plan to allow custom packages to disable pockets and components.
Let's stay with the current warning as a solution as it solves the problem with the current features we offer.

**Comment by amylily1011** [comment]
@lilyvidenova @clagom  I've happy with the current solution, if you good to go can you give it a +1?

**Comment by clagom** [comment]
@amylily1011, as @lilyvidenova mentioned, are you proposing we keep the current design, or to build the proposed design ([here](https://app.zeplin.io/project/5ce5423a25863c1e0d7abb27/screen/5defadfa772834b3a28f57c8))?

**Comment by amylily1011** [comment]
@lilyvidenova, build the one on Zeplin.

**Comment by clagom** [comment]
Cool, is it worth exploring the rest ux/design wise? Could be at least a backlog issue?
CC @cristinadresch

**Comment by cristinadresch** [comment]
@amylily1011 to create an issue for build

**Comment by sparkiegeek** [comment]
> @amylily1011 to create an issue for build

@amylily1011 did you create this issue? Can you link it please? Am trying to update https://bugs.launchpad.net/maas/+bug/1851276
