### ISSUE TITLE
Unable to login after creating admin user

### ISSUE THREAD

**Issue by squidsoup** [canonical-web-and-design/maas-ui#662]
**Describe the bug**
After creating a new admin user and logging out, unable to login using that user/password. The server returns:

```{"__all__": ["Please enter a correct username and password. Note that both fields may be case-sensitive."]}```

**MAAS version**
master/2.7rc

**To Reproduce**
1. Create a new user
2. Logout
3. Attempt to login as that user.

**Expected behavior**
The new user can login.

**Additional context**
This only seems to occur when creating an admin user, creating a normal user does appear to work.

**Comment by Caleb-Ellis** [comment]
@squidsoup Hmm I don't seem to be having this issue. I've added an admin `test` pw `testtest` and I can log in and do admin stuff just fine. I've logged in and out about 5 times without a problem.

![screenshot_3](https://user-images.githubusercontent.com/25733845/72428494-1b3ba980-378e-11ea-9349-96ec3b39aa38.png)

**Comment by squidsoup** [comment]
This seems to be working fine now. 🤷‍♂
