### ISSUE TITLE
Revisit UX of script status tooltip + icon

### ISSUE THREAD

**Issue by Caleb-Ellis** [canonical-web-and-design/maas-ui#665]
@squidsoup Yeah I'm pretty sure the angular tooltip is wrong because it assumes any non-passing status == failed. I opted to just remove the tooltip entirely if the status is pending or running because I figured the icon was enough, but maybe my UX-fu is off.

@lilyvidenova any thoughts on if tooltips should show for machines with pending/running tests, and if so what should they say?

_Originally posted by @Caleb-Ellis in https://github.com/canonical-web-and-design/maas-ui/pull/648_

**Comment by Caleb-Ellis** [comment]
> @lilyvidenova oh yeah also I added a warning icon and tooltip if a machine hasn't run any tests of that type yet ("Machine has not run any tests of this type.")

**Comment by lilyvidenova** [comment]
@Caleb-Ellis UX-fu on point as per 👍

**Comment by Caleb-Ellis** [comment]
TODO: remove warning icon for machines that have not run tests
