### ISSUE TITLE
Update privacy policy

### ISSUE THREAD

**Issue by squidsoup** [canonical-web-and-design/maas-ui#698]
We directly link to the company privacy policy via https://ubuntu.com/legal/ but potentially need a more direct link to https://ubuntu.com/legal/data-privacy. That page does disclose that we have opt-out error tracking, but the paragraph refers to the error tracking in Ubuntu, not MAAS or our webapps, so it may not be appropriate to link there for MAAS.

A decision needs to be made about how we communicate that we have opt-out error tracking and analytics in MAAS. Potentially we need a new privacy policy on maas.io that we can link to? Is there anyone from legal in the office you could speak to @lilyvidenova?

**Comment by lilyvidenova** [comment]
Lydia will work with Peter on updating the text in the general privacy policy that covers MAAS as well.
