### ISSUE TITLE
Add GA event to `enable_analytics` checkbox

### ISSUE THREAD

**Issue by squidsoup** [canonical-web-and-design/maas-ui#703]

**Comment by huwshimi** [comment]
This is currently sent when the form is saved, but could easily be moved to when the checkbox is clicked: https://github.com/canonical-web-and-design/maas-ui/blob/master/ui/src/app/settings/views/Configuration/GeneralForm/GeneralForm.js#L35.

**Comment by squidsoup** [comment]
Oh excellent, I suppose there's no reason to keep this open @huwshimi?

**Comment by huwshimi** [comment]
@squidsoup if you're happy for the event to be on save rather than clicking the checkbox then this can be closed.

**Comment by squidsoup** [comment]
@huwshimi probably no need to overcomplicate this, we're getting the data we're interested in with the current implementation.
