### ISSUE TITLE
Don't show machine/pool count until fully loaded

### ISSUE THREAD

**Issue by Caleb-Ellis** [canonical-web-and-design/maas-ui#725]
I implemented this 1:1 with the angular machine list which has this same issue. When machines are loading the count incorrectly says "0 Machines", or whatever is still currently loading into state in batches. @matthewpaulthomas has suggested removing the count until all have loaded, which I think is clearer and not misleading.

**Comment by lilyvidenova** [comment]
+1, thanks @matthewpaulthomas
