### ISSUE TITLE
Document how to serve production UI builds locally

### ISSUE THREAD

**Issue by Caleb-Ellis** [canonical-web-and-design/maas-ui#739]
There's a few things to consider:
- Routing between the Angular and React sides of the app
- Handling JS routing
- CORS

**Comment by squidsoup** [comment]
@Caleb-Ellis do you think we still need this, or should we just link to discourse post from sparkie?

**Comment by huwshimi** [comment]
@Caleb-Ellis do you think this is covered by the single-spa work and the new hacking docs? Particularly running the prod build details: https://github.com/canonical-web-and-design/maas-ui/blob/master/HACKING.md#running-maas-ui-from-a-development-maas
