### ISSUE TITLE
Make action spinners generic

### ISSUE THREAD

**Issue by huwshimi** [canonical-web-and-design/maas-ui#743]
Investigate making a generic way to handle the spinners that appear when performing an action from the machine list context menus.

**Comment by cristinadresch** [comment]
@huwshimi assigning this one too for next iteration, but if you think its too much we can keep this one separate from this in-table actions epic. Just let me know

**Comment by cristinadresch** [comment]
@huwshimi we removed this one for this iteration for now

**Comment by Caleb-Ellis** [comment]
@huwshimi I think this has been handled with the machine processing stuff, right? Closing, but reopen if I've got this wrong

**Comment by huwshimi** [comment]
@Caleb-Ellis yep, thanks I think this is as good as it can be for now.
