### ISSUE TITLE
Logging out of Angular pages results in a "Method Not Allowed" error in production builds

### ISSUE THREAD

**Issue by Caleb-Ellis** [canonical-web-and-design/maas-ui#759]
https://bugs.launchpad.net/maas/+bug/1862345
> This is with MAAS 2.7.0~rc4-8224-g.fe803ddc9-0ubuntu1-18.04.1.
>
> When logging out from any of the non-react views, I'm presented with a bare error page:
>
>  Method Not Allowed
>  Your browser approached me (at /MAAS) with the method "GET". I only allow the method HEAD here.
>
>If I log out from the settings page, it works, and I'm presented with the login page.

This doesn't appear to be the case when running the 2.7 branch locally.

**Comment by Caleb-Ellis** [comment]
Hey @huwshimi I've assigned you because you did the original work on the auth api. I think I might have broken something with [this PR](https://github.com/canonical-web-and-design/maas-ui/pull/752), but I'm not sure what or how. Basically the original issue was that you could enter into the password field something like `password&foo=bar` and they would be sent as separate parameters, which I thought I'd fixed.

**Comment by sparkiegeek** [comment]
https://github.com/canonical-web-and-design/maas-ui/blob/2.7/legacy/src/app/entry.js#L350
