### ISSUE TITLE
Investigate caching issues on new releases

### ISSUE THREAD

**Issue by Caleb-Ellis** [canonical-web-and-design/maas-ui#766]
Updating the MAAS version on karura (for example) requires a hard refresh for UI updates to show up. IIRC, css updates show up correctly, but markup and JS updates do not. We should investigate why this is happening.

**Comment by huwshimi** [comment]
Dupe of https://github.com/canonical-web-and-design/maas-ui/issues/1497 (keeping #1397 as it has an attached Launchpad bug).
