### ISSUE TITLE
Investigate why development/production builds differ.

### ISSUE THREAD

**Issue by Caleb-Ellis** [canonical-web-and-design/maas-ui#768]
In development in some cases markup is automagically fixed and redirects are more forgiving. We should figure out why this isn't the case for production and align the two as much as possible.

**Comment by squidsoup** [comment]
This needs more detail @Caleb-Ellis - which markup in question? Which redirects behave differently?

**Comment by Caleb-Ellis** [comment]
This hasn't been an issue for a while now - we've fixed it since the start of our single-spa journey
