### ISSUE TITLE
Improve perceived performance of machine list.

### ISSUE THREAD

**Issue by Caleb-Ellis** [canonical-web-and-design/maas-ui#777]
Navigating to the machine list while everything is loaded into state has some noticeable lag while rendering to the DOM. Nowhere near as much as the angular version, but it's still present. We should improve the perceived performance by rendering something small at first before rendering the table rows.

**Comment by squidsoup** [comment]
@Caleb-Ellis are you referring to development or production? Would be good to have some timings here too.

**Comment by Caleb-Ellis** [comment]
This no longer seems to be an issue with the new performance improvements.
