### ISSUE TITLE
Investigate feature flags

### ISSUE THREAD

**Issue by squidsoup** [canonical-web-and-design/maas-ui#783]
It would be nice to have a way to conveniently enable/disable features in production builds based on feature flags. This would make the process of disabling features potentially easier as we branch for MAAS RCs.

**Comment by huwshimi** [comment]
Might be good to see if @hatched has anything planned for the dashboard. It might be nice to pick the same tool.

**Comment by hatched** [comment]
The dashboard needs to switch to an external file for configuration so I was going to add the flag values in there. We also now have a settings page where these types of things can be toggled if we'd like to add client side control to them. I can show in further detail if you'd like.

**Comment by huwshimi** [comment]
We don't have any need for feature flags at the moment so I'll close this.
