### ISSUE TITLE
Refactor redux action type names

### ISSUE THREAD

**Issue by squidsoup** [canonical-web-and-design/maas-ui#785]
Currently our action types are in the form `FETCH_USER_START` and `DELETE_MACHINE_SUCCESS`. 

The redux-toolkit proposes a different approach where action type names are namespaced under the model name, which I think is much nicer, e.g. `user/fetch/start` and `machine/delete/success`. 

This would be a large refactor, but I think it would be a worthwhile improvement.

Thoughts, @huwshimi, @Caleb-Ellis?

**Comment by huwshimi** [comment]
Fine by me either way.

**Comment by Caleb-Ellis** [comment]
Sounds good to me! I think it's nicer having the model as the first thing.

**Comment by squidsoup** [comment]
This is about ensuring all action types have the same shape as well, which allows us to generalise some generator functions - currently we have some actions in the form `VERB_MODEL/VERB_MODEL_START` and some simply as `VERB/VERB_START` without a model.

**Comment by Caleb-Ellis** [comment]
This issue will be fixed with the migration to slices, e.g. in https://github.com/canonical-web-and-design/maas-ui/issues/1403
