### ISSUE TITLE
Prepare for machine details user testing

### ISSUE THREAD

**Issue by lilyvidenova** [canonical-web-and-design/maas-ui#786]

**Comment by lilyvidenova** [comment]
[Document](https://docs.google.com/document/d/1HA48S5-4ztqXBdFsflBOdqFCf1zL7_DAClELzAhhqzM/edit#)

**Comment by lilyvidenova** [comment]
I spoke to Adam, he gave me a list of people to contact. He also said he will work on providing us with an environment that we can use and restore to a known state after each participant.

**Comment by anthonydillon** [comment]
That's awesome. What about reaching out to the guy from Ubuntu masters he
will have a team that use it?
