### ISSUE TITLE
Generalise table menu link creation

### ISSUE THREAD

**Issue by Caleb-Ellis** [canonical-web-and-design/maas-ui#793]
> I wonder if this whole section of creating the menu links could be generalised somehow? Like a custom hook that you just pass in the allowed actions, something like `const menuLinks = useTableMenuLinks(["acquire", "release"])`. :man_shrugging:

_Originally posted by @Caleb-Ellis in https://github.com/canonical-web-and-design/maas-ui/pull/791_

**Comment by huwshimi** [comment]
This should also include the title from general.machineActions.data as note here: https://github.com/canonical-web-and-design/maas-ui/pull/796#discussion_r379306223
