### ISSUE TITLE
Complete migration to redux-toolkit

### ISSUE THREAD

**Issue by squidsoup** [canonical-web-and-design/maas-ui#801]
## Actions
The following actions should be migrated to `createAction`:

- [ ] base/actions/auth
- [ ] base/actions/general
- [ ] base/actions/licenseKeys
- [ ] base/actions/machine
- [ ] base/actions/scripts

## Reducers
The following reducers should be migrated to `createReducer`:

- [ ] base/reducers/auth
- [ ] base/reducers/general
- [ ] base/reducers/licensekeys
- [ ] base/reducers/machine
- [ ] base/reducers/packagerepository
- [ ] base/actions/scripts

**Comment by Caleb-Ellis** [comment]
@squidsoup can we close this?

**Comment by Caleb-Ellis** [comment]
This will be addressed in the slices work
