### ISSUE TITLE
Fix expectSaga timeouts in websockets.test.js

### ISSUE THREAD

**Issue by squidsoup** [canonical-web-and-design/maas-ui#803]
**Describe the bug**
Currently two tests timeout with the following warning:

```
[WARNING]: Saga exceeded async timeout of 250ms
```

The tests in question are:

* `it("connects to a WebSocket")...` 
* `it("raises an error if no csrftoken exists")...`

This suggests there may be an infinite loop somewhere, or we're failing to `PUT` an expected action. 

**MAAS version**
maas-ui 1.0.0

**To Reproduce**
Run `yarn test websockets.test.js` from `ui/`

**Comment by huwshimi** [comment]
I think this is expected behaviour. Because we wait for actions with `takeEvery` the timeout is used to cancel the saga. More details here: http://redux-saga-test-plan.jeremyfairbank.com/integration-testing/timeout.html
