### ISSUE TITLE
CPU/Mem overcommit settings look disabled when editing a Pod 

### ISSUE THREAD

**Issue by lilyvidenova** [canonical-web-and-design/maas-ui#807]
[LP bug 1863723](https://bugs.launchpad.net/maas/+bug/1863723)

In the settings tab for Virsh Pods, the CPU and memory overcommit ratio sliders look like they're disabled even when editing settings.

The slider actually works, but you can't directly enter a number in the input field (maybe that's intentional?) and the fact that the field is greyed out feels like the setting itself can't be changed.

**Comment by Caleb-Ellis** [comment]
Duplicate of https://github.com/canonical-web-and-design/maas-ui/issues/1546
