### ISSUE TITLE
No spinner when checking power

### ISSUE THREAD

**Issue by lilyvidenova** [canonical-web-and-design/maas-ui#813]
The power icon should be changed to the spinner icon when checking power for a machine when using the in-table actions

**Comment by huwshimi** [comment]
Related to: https://github.com/canonical-web-and-design/maas-ui/issues/781

**Comment by Caleb-Ellis** [comment]
Still valid

**Comment by Caleb-Ellis** [comment]
Actually a duplicate of #781
