### ISSUE TITLE
Update text on Settings > General 

### ISSUE THREAD

**Issue by lilyvidenova** [canonical-web-and-design/maas-ui#828]
The checkbox text should be updated to: 

Enable analytics in MAAS UI to shape improvements in user experience.

with help text:

The analytics used in MAAS UI are Google Analytics and Sentry Error Tracking.

![image.png](https://images.zenhubusercontent.com/5af976724b5806bc2bd30860/6199054d-6dc8-477e-a16d-664755ee8212)

**Comment by squidsoup** [comment]
> The checkbox text should be updated to:
> 
> Enable analytics in MAAS UI to shape improvements in user experience.
> 

I think we should probably just say "MAAS", as "MAAS UI" is only something we talk about internally.

**Comment by squidsoup** [comment]
Actually, now that I think about it, the user is already using MAAS, so how about "Enable analytics to shape improvements to user experience."
