### ISSUE TITLE
Migrate cypress CI from circleci to github actions

### ISSUE THREAD

**Issue by squidsoup** [canonical-web-and-design/maas-ui#839]
Cypress E2E test CI needs to be migrated to github actions. Cypress have written a [nice blog post about this](https://www.cypress.io/blog/2019/11/20/drastically-simplify-your-testing-with-cypress-github-action/) that might be useful.

**Comment by squidsoup** [comment]
Blocked until Github provide a means of running cypress on PRs from a fork on github actions.

**Comment by Caleb-Ellis** [comment]
This is done!
