### ISSUE TITLE
Error message displaying mark-up

### ISSUE THREAD

**Issue by anthonydillon** [canonical-web-and-design/maas-ui#858]
**Describe the bug**
When logging in to maas-ui on port 5401, the ui renders a broken login screen. It would be nice to have a message in development suggesting that 5400 is the correct port.

**MAAS version**
Master

**To Reproduce**
1. Point the MAAS_URL to karura
2. Run `dotrun`
3. Try to login

**Expected behavior**
The error should just show the message within the HTML.

**Screenshots**
![image](https://user-images.githubusercontent.com/1413534/75759017-c5ff2b80-5d2c-11ea-97eb-753d9a3bf5c3.png)

**Comment by squidsoup** [comment]
Hey @anthonydillon, I can't reproduce this on master.

**Comment by anthonydillon** [comment]
This was due to using the wrong port in development. Still worth fixing but low priority.
