### ISSUE TITLE
On the network tab there are rogue checkboxes

### ISSUE THREAD

**Issue by lilyvidenova** [canonical-web-and-design/maas-ui#860]
**Describe the bug**
There are invisible and hidden checkboxes that change the cursor when you hover over them, to replicate create a bond and hover over the bonded interfaces.

**MAAS version**
Edge snap

**LP issue**
N/A

**To Reproduce**
1. Go to Network tab
2. Create a bond
3. Hover over bonded interface

**Expected behavior**
Cursor not to change

**Comment by Caleb-Ellis** [comment]
This is a small and harmless bug. I'm closing for now with the idea that this will be fixed in the React migration. It will be impressive if this is still an issue after that.
