### ISSUE TITLE
Investigate slowness (infinite loop) when using the UI for a while

### ISSUE THREAD

**Issue by Caleb-Ellis** [canonical-web-and-design/maas-ui#872]
The UI can become unresponsive in production.

## Steps to replicate
Switch repeatedly between any two views.

**Comment by pud-nats** [comment]
we should backport this to 2.7

**Comment by cristinadresch** [comment]
@lilyvidenova to add info

**Comment by squidsoup** [comment]
I've released a new version of maas-ui with source maps enabled, which should hopefully help us debug this. Awaiting a new maas release so that this can be tested on bolla.

**Comment by squidsoup** [comment]
Some [relevant angularjs discussion](https://github.com/angular/angular.js/issues/4864).

**Comment by squidsoup** [comment]
It appears we have a leak.

![image](https://user-images.githubusercontent.com/130286/78304659-b8db9380-759b-11ea-8eb7-e269474df30a.png)
_The result of switching repeatedly between Machine List and Machine Details over a 10s period._

Looking at the heap profile, we appear to have a large amount of detached nodes.

![image](https://user-images.githubusercontent.com/130286/78304820-0b1cb480-759c-11ea-8c33-7c9b0d6f1050.png)

**Comment by squidsoup** [comment]
Not a V8 specific issue, the leak exists in Firefox as well.

**Comment by anthonydillon** [comment]
Kit, was there a fix delivered or is this a bug we are willing to live with? I don't see a solution comment.

**Comment by lilyvidenova** [comment]
@anthonydillon isn't this fixed in [#937](https://app.zenhub.com/workspace/o/canonical-web-and-design/maas-ui/issues/937)?

**Comment by anthonydillon** [comment]
@lilyvidenova Sorry missing the linked PR thanks.

**Comment by squidsoup** [comment]
@anthonydillon fixed in versions v1.1.1 and v0.2.8 (backported to 2.7).
