### ISSUE TITLE
Add note to broken machines visual design

### ISSUE THREAD

**Issue by lyubomir-popov** [canonical-web-and-design/maas-ui#901]
zpl://project?pid=5e6a623cde850113ba28d75b&seid=5e70e416cdaa17b61269f39b

**Comment by lyubomir-popov** [comment]
@lilyvidenova added a few screens to zeplin for discussion. zpl://project?pid=5e6a623cde850113ba28d75b&seid=5e70e416cdaa17b61269f39b

**Comment by lilyvidenova** [comment]
Let's keep it simple for now and simply display the name + note of the machine as well as the message that whatever is there will be overwritten. [The design on Zeplin](https://zpl.io/2pAO8XE).

**Comment by lilyvidenova** [comment]
@lyubomir-popov can you suggest what should the options when there are no notes to be overwritten looks like? After the last design review we moved the help text to the right of the input field, with the addition of the list to the right you have moved the list to under the input - I'd believe this should remain in the same place regardless of whether there is a list of machines or not.

**Comment by anthonydillon** [comment]
For what its worth I believe the list should remain and the layout should be consistent. So if there is no note to override the current note column is still present but is just empty.

**Comment by lilyvidenova** [comment]
@anthonydillon The list of machines is already displayed in full underneath the window - what will duplicating the names of the machines add to the interaction?

**Comment by anthonydillon** [comment]
The focus of the user is squarely on the note panel and not all machines are visible below so it's good to have all the information available in one place to decided if your confident the note can be applied without losing something. I am not sure if this has changed now that there is a second note available.

**Comment by lilyvidenova** [comment]
@anthonydillon - Lyubo framed this very well at stand-up today, when you copy files from one folder to the other you don't get a pop-up telling you the file will be moved for every single file, just for the ones that have a conflict. I agree this is a very similar situation, there is a fine line between being helpful and just showing all the information because we can.
