### ISSUE TITLE
Mark broken and add note on machine listing

### ISSUE THREAD

**Issue by lilyvidenova** [canonical-web-and-design/maas-ui#902]
[Design](https://app.zeplin.io/project/5e6a623cde850113ba28d75b/dashboard?seid=5e7488c8056e1a016b179173)

- using the error description field 
- showing it as the second line of the Status on the machine listing

**Comment by cristinadresch** [comment]
@lilyvidenova to create LP bug and add description to this issue

**Comment by lilyvidenova** [comment]
[Updated deisng](https://app.zeplin.io/project/5e6a623cde850113ba28d75b/dashboard?seid=5e7d038ed31b368f0881a194)

**Comment by lilyvidenova** [comment]
@Caleb-Ellis or @squidsoup could you please [file a bug](https://bugs.launchpad.net/maas/+filebug) for the error description to be surfaced, please? I don't know where exactly it should be surfaced so I'm not sure how to phrase it.

**Comment by Caleb-Ellis** [comment]
Blocked on https://bugs.launchpad.net/maas/+bug/1871003

**Comment by lilyvidenova** [comment]
This is now unblocked: https://bugs.launchpad.net/maas/+bug/1871003

**Comment by squidsoup** [comment]
> @squidsoup is this a dupe of the work you're doing now?

It is yep, I [created a new epic](https://app.zenhub.com/workspaces/maas-squad-593fb7e786156437e0725052/issues/canonical-web-and-design/maas-design/923) for this, since it will need design QA too.
