### ISSUE TITLE
Disable sentry reporting in local development

### ISSUE THREAD

**Issue by anthonydillon** [canonical-web-and-design/maas-ui#950]
It seems sentry is [reporting errors on local development] (https://sentry.is.canonical.com/canonical/maas-ui/issues/7947/?referrer=alert_email). This dilutes the importance of actual errors from production.

**Comment by squidsoup** [comment]
Thanks @anthonydillon, we're aware, but it can't be resolved until https://github.com/canonical-web-and-design/maas-ui/issues/713 is closed, which hopefully [my branch](https://github.com/canonical-web-and-design/maas-ui/pull/947) proposed today fixes!

**Comment by squidsoup** [comment]
Closed via #713
