### ISSUE TITLE
Login form should display warning to user that no admin exists

### ISSUE THREAD

**Issue by squidsoup** [canonical-web-and-design/maas-ui#969]
**Describe the bug**
Apparently this used to exist in the angular login form, but we seem to have lost it along the way.

**MAAS version**
? (try master)

**To Reproduce**
1. Login without an admin user

**Expected behavior**
This needs clarification (we should grep the code for the old warning).

**Comment by Caleb-Ellis** [comment]
It looks like the old login template (before the UI split) had this conditional:
``` html
{% if no_users and not external_auth_url %}
    <div class="col-8">
        <h1 class="p-heading--four">No admin user has been created yet</h1>
        <p>Use the "init" administration command to create one:</p>
        <pre>{{ create_command }} init</pre>
        <form method="get" action="{% url 'login' %}">
            <button type="submit" class="p-button--positive">Login</button>
        </form>
    </div>
{% else %}
```

Originally, the login endpoint returned:
``` python
extra_context = {
    'no_users': UserProfile.objects.all_users().count() == 0,
    'create_command': django_settings.MAAS_CLI,
    'external_auth_url': Config.objects.get_config('external_auth_url'),
    }
```

But now it returns:
``` python
return JsonResponse(
    {
        "authenticated": request.user.is_authenticated,
        "external_auth_url": request.external_auth_info.url
        if request.external_auth_info
        else None,
    }
)
```

Looks like we'll need the login endpoint to return `no_users` again.

**Comment by albertodonato** [comment]
Side note, when there are no users (and no external auth), the message should tell users to run 
```
sudo maas createadmin
```

**Comment by Caleb-Ellis** [comment]
@albertodonato I have a PR up that broke our CI tests here: https://github.com/canonical-web-and-design/maas-ui/pull/983

In CI a MAAS is set up with a single admin created from `maas init`, however the api is returning `no_users: true`. Is that right? Is there some difference between an admin created from `maas init` over `maas createadmin` that means that it shouldn't be able to log in to the UI?
