### ISSUE TITLE
[React] Clearing search is not responsive

### ISSUE THREAD

**Issue by anthonydillon** [canonical-web-and-design/maas-ui#978]
**Describe the bug**
When searching on the machine listing and hitting the clear X the input only clears when the table re-renders.

**MAAS version**
2.8.0~alpha1 (8344-g.b90a00a87)

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to http://bolla.internal:5240/MAAS/r/machines
2. Filter the list
3. Click the clear X in the input
4. See that nothing happens for a while.

**Expected behaviour**
It would be better to clear the input and maybe show the table is rendering.

**Comment by squidsoup** [comment]
This isn't a bug as such. As the search input is a controlled input, it's value is set by state, which requires a rerender, and as we have not implemented virtualisation, this is slow.

**Comment by sparkiegeek** [comment]
I think this is solved with the debounce changes?

**Comment by Caleb-Ellis** [comment]
Fixed in #1005
