### ISSUE TITLE
Switching between Angular.js and React views shouldn't discard websocket

### ISSUE THREAD

**Issue by sparkiegeek** [canonical-web-and-design/maas-ui#998]
**Describe the bug**
When switching between React views and Angular.js ones (e.g. machine listing to machine details) we see a brief flash of an error message saying "The server connection failed" and in DevTools I see *two* requests to open the websocket. 

**maas-ui version**
 revision 65aea593483e4c4b5e077a4afa3d2b95746bd2bc

**MAAS version**
2.8.0b1

**LP issue**
No

**To Reproduce**
1. Go to http://bolla.internal:5240/MAAS/r/machines
2. Click on a machine
3. See error

**Expected behavior**
At *absolute most* one websocket request, ideally 0

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Browser: Firefox
 - Version: 75.0

**Additional context**

**Comment by lilyvidenova** [comment]
[Video](https://drive.google.com/open?id=1sEn0jGz5dpex9trxbvi5OQY7Z78Tw899)

**Comment by huwshimi** [comment]
Done in https://github.com/canonical-web-and-design/maas-ui/pull/1233
